HTMLArea.BlockStyle=HTMLArea.Plugin.extend({constructor:function(editor,pluginName){this.base(editor,pluginName);},configurePlugin:function(editor){this.cssLoaded=false;this.cssTimeout=null;this.cssParseCount=0;this.cssArray=new Object();this.classesUrl=this.editorConfiguration.classesUrl;this.pageTSconfiguration=this.editorConfiguration.buttons.blockstyle;this.tags=this.pageTSconfiguration.tags;if(!this.tags){this.tags=new Object();}
if(typeof(this.editorConfiguration.classesTag)!=="undefined"){if(this.editorConfiguration.classesTag.div){if(!this.tags.div){this.tags.div=new Object();}
if(!this.tags.div.allowedClasses){this.tags.div.allowedClasses=this.editorConfiguration.classesTag.div;}}
if(this.editorConfiguration.classesTag.td){if(!this.tags.td){this.tags.td=new Object();}
if(!this.tags.td.allowedClasses){this.tags.td.allowedClasses=this.editorConfiguration.classesTag.td;}}
if(this.editorConfiguration.classesTag.table){if(!this.tags.table){this.tags.table=new Object();}
if(!this.tags.table.allowedClasses){this.tags.table.allowedClasses=this.editorConfiguration.classesTag.table;}}}
var allowedClasses;for(var tagName in this.tags){if(this.tags.hasOwnProperty(tagName)){if(this.tags[tagName].allowedClasses){allowedClasses=this.tags[tagName].allowedClasses.trim().split(",");for(var cssClass in allowedClasses){if(allowedClasses.hasOwnProperty(cssClass)){allowedClasses[cssClass]=allowedClasses[cssClass].trim().replace(/\*/g,".*");}}
this.tags[tagName].allowedClasses=new RegExp("^("+allowedClasses.join("|")+")$","i");}}}
this.showTagFreeClasses=this.pageTSconfiguration.showTagFreeClasses||this.editorConfiguration.showTagFreeClasses;this.prefixLabelWithClassName=this.pageTSconfiguration.prefixLabelWithClassName;this.postfixLabelWithClassName=this.pageTSconfiguration.postfixLabelWithClassName;var pluginInformation={version:"1.4",developer:"Stanislas Rolland",developerUrl:"http://www.sjbr.ca/",copyrightOwner:"Stanislas Rolland",sponsor:this.localize("Technische Universitat Ilmenau"),sponsorUrl:"http://www.tu-ilmenau.de/",license:"GPL"};this.registerPluginInformation(pluginInformation);var dropDownId='BlockStyle';var fieldLabel=this.pageTSconfiguration.fieldLabel;if(Ext.isEmpty(fieldLabel)&&this.isButtonInToolbar('I[Block style label]')){fieldLabel=this.localize('Block style label');}
var dropDownConfiguration={id:dropDownId,tooltip:this.localize(dropDownId+'-Tooltip'),fieldLabel:fieldLabel,options:[[this.localize('No style'),'none']],action:'onChange',storeFields:[{name:'text'},{name:'value'},{name:'style'}],tpl:'<tpl for="."><div ext:qtip="{value}" style="{style}text-align:left;font-size:11px;" class="x-combo-list-item">{text}</div></tpl>'};if(this.pageTSconfiguration.width){dropDownConfiguration.width=parseInt(this.pageTSconfiguration.width,10);}
if(this.pageTSconfiguration.listWidth){dropDownConfiguration.listWidth=parseInt(this.pageTSconfiguration.listWidth,10);}
if(this.pageTSconfiguration.maxHeight){dropDownConfiguration.maxHeight=parseInt(this.pageTSconfiguration.maxHeight,10);}
this.registerDropDown(dropDownConfiguration);return true;},onChange:function(editor,combo,record,index){var className=combo.getValue();this.editor.focus();var blocks=this.getSelectedBlocks();for(var k=0;k<blocks.length;++k){var parent=blocks[k];while(parent&&!HTMLArea.isBlockElement(parent)&&parent.nodeName.toLowerCase()!="img"){parent=parent.parentNode;}
if(!k){var tagName=parent.tagName.toLowerCase();}
if(parent.tagName.toLowerCase()==tagName){this.applyClassChange(parent,className);}}},applyClassChange:function(node,className){if(className=="none"){var classNames=node.className.trim().split(" ");for(var i=classNames.length;--i>=0;){if(!HTMLArea.reservedClassNames.test(classNames[i])){HTMLArea._removeClass(node,classNames[i]);if(node.nodeName.toLowerCase()==="table"&&this.getPluginInstance('TableOperations')){this.getPluginInstance('TableOperations').removeAlternatingClasses(node,classNames[i]);this.getPluginInstance('TableOperations').removeCountingClasses(node,classNames[i]);}
break;}}}else{var nodeName=node.nodeName.toLowerCase();if(this.tags&&this.tags[nodeName]&&this.tags[nodeName].allowedClasses){if(this.tags[nodeName].allowedClasses.test(className)){HTMLArea._addClass(node,className);}}else if(this.tags&&this.tags.all&&this.tags.all.allowedClasses){if(this.tags.all.allowedClasses.test(className)){HTMLArea._addClass(node,className);}}else{HTMLArea._addClass(node,className);}
if(nodeName==="table"&&this.getPluginInstance('TableOperations')){this.getPluginInstance('TableOperations').reStyleTable(node);}}},getSelectedBlocks:function(){var block,range,i=0,blocks=[];var statusBarSelection=this.editor.statusBar?this.editor.statusBar.getSelection():null;if(Ext.isGecko){var selection=this.editor._getSelection();try{while((range=selection.getRangeAt(i++))){block=this.editor.getParentElement(selection,range);blocks.push(statusBarSelection?statusBarSelection:block);}}catch(e){}}else{blocks.push(statusBarSelection?statusBarSelection:this.editor.getParentElement());}
return blocks;},onGenerate:function(){this.editor.iframe.mon(this.editor,'modeChange',this.onModeChange,this);if(!Ext.isIE){this.generate(this.editor,'BlockStyle');}},onUpdateToolbar:function(button,mode,selectionEmpty,ancestors){if(mode==='wysiwyg'){this.generate(this.editor,button.itemId);}},onModeChange:function(mode){if(this.getEditorMode()==="wysiwyg"){this.generate(this.editor,"BlockStyle");}},generate:function(editor,dropDownId){if(this.cssLoaded&&this.getEditorMode()==='wysiwyg'&&this.editor.isEditable()){this.updateValue(dropDownId);}else{if(this.cssTimeout){window.clearTimeout(this.cssTimeout);this.cssTimeout=null;}
if(this.classesUrl&&(typeof(HTMLArea.classesLabels)==='undefined')){this.getJavascriptFile(this.classesUrl,function(options,success,response){if(success){try{if(typeof(HTMLArea.classesLabels)==='undefined'){eval(response.responseText);this.appendToLog('generate','Javascript file successfully evaluated: '+this.classesUrl);}}catch(e){this.appendToLog('generate','Error evaluating contents of Javascript file: '+this.classesUrl);}}
this.buildCssArray(this.editor,dropDownId);});}else{this.buildCssArray(this.editor,dropDownId);}}},updateValue:function(dropDownId){var dropDown=this.getButton(dropDownId);if(dropDown){var classNames=new Array();var tagName=null;var statusBarSelection=this.editor.statusBar?this.editor.statusBar.getSelection():null;var parent=statusBarSelection?statusBarSelection:this.editor.getParentElement();while(parent&&!HTMLArea.isBlockElement(parent)&&parent.nodeName.toLowerCase()!="img"){parent=parent.parentNode;}
if(parent){tagName=parent.nodeName.toLowerCase();classNames=this.getClassNames(parent);}
if(tagName&&tagName!=="body"){this.buildDropDownOptions(dropDown,tagName);this.setSelectedOption(dropDown,classNames);}else{this.initializeDropDown(dropDown);dropDown.setDisabled(true);}}},getClassNames:function(node){var classNames=new Array();if(node){if(node.className&&/\S/.test(node.className)){classNames=node.className.trim().split(" ");}
if(HTMLArea.reservedClassNames.test(node.className)){var cleanClassNames=new Array();var j=-1;for(var i=0;i<classNames.length;++i){if(!HTMLArea.reservedClassNames.test(classNames[i])){cleanClassNames[++j]=classNames[i];}}
return cleanClassNames;}}
return classNames;},initializeDropDown:function(dropDown){var store=dropDown.getStore();store.removeAll(false);store.insert(0,new store.recordType({text:this.localize('No style'),value:'none'}));dropDown.setValue('none');},buildDropDownOptions:function(dropDown,tagName){var store=dropDown.getStore();var cssArray=new Array();this.initializeDropDown(dropDown);if(typeof(this.cssArray.all)!=="undefined"){var cssArrayAll=this.cssArray.all;if(this.tags&&this.tags[tagName]&&this.tags[tagName].allowedClasses){var allowedClasses=this.tags[tagName].allowedClasses;for(var cssClass in cssArrayAll){if(cssArrayAll.hasOwnProperty(cssClass)&&allowedClasses.test(cssClass)){cssArray[cssClass]=cssArrayAll[cssClass];}}}else{for(var cssClass in cssArrayAll){if(cssArrayAll.hasOwnProperty(cssClass)){cssArray[cssClass]=cssArrayAll[cssClass];}}}}
if(typeof(this.cssArray[tagName])!=="undefined"){var cssArrayTagName=this.cssArray[tagName];if(this.tags&&this.tags[tagName]&&this.tags[tagName].allowedClasses){var allowedClasses=this.tags[tagName].allowedClasses;for(var cssClass in cssArrayTagName){if(cssArrayTagName.hasOwnProperty(cssClass)&&allowedClasses.test(cssClass)){cssArray[cssClass]=cssArrayTagName[cssClass];}}}else{for(var cssClass in cssArrayTagName){if(cssArrayTagName.hasOwnProperty(cssClass)){cssArray[cssClass]=cssArrayTagName[cssClass];}}}
var sortedCssArray=new Object();var cssArrayKeys=new Array();for(var cssClass in cssArray){if(cssArray.hasOwnProperty(cssClass)){cssArrayKeys.push(cssClass);}}
function compare(a,b){x=cssArray[a];y=cssArray[b];return((x<y)?-1:((x>y)?1:0));}
cssArrayKeys=cssArrayKeys.sort(compare);for(var i=0;i<cssArrayKeys.length;++i){sortedCssArray[cssArrayKeys[i]]=cssArray[cssArrayKeys[i]];}
cssArray=sortedCssArray;}
for(var cssClass in cssArray){if(cssArray.hasOwnProperty(cssClass)&&cssArray[cssClass]){if(cssClass=='none'){store.getAt(0).set('text',cssArray[cssClass]);}else{var style=null;if(!this.editor.config.disablePCexamples){if(HTMLArea.classesValues[cssClass]&&!HTMLArea.classesNoShow[cssClass]){style=HTMLArea.classesValues[cssClass];}else if(/-[0-9]+$/.test(cssClass)&&HTMLArea.classesValues[RegExp.leftContext+'-']){style=HTMLArea.classesValues[RegExp.leftContext+'-'];}}
store.add(new store.recordType({text:cssArray[cssClass],value:cssClass,style:style}));}}}},setSelectedOption:function(dropDown,classNames,noUnknown,defaultClass){var store=dropDown.getStore();dropDown.setValue('none');if(classNames.length){var index=store.findExact('value',classNames[classNames.length-1]);if(index!=-1){dropDown.setValue(classNames[classNames.length-1]);if(!defaultClass){store.getAt(0).set('text',this.localize('Remove style'));}}
if(index==-1&&!noUnknown){store.add(new store.recordType({text:this.localize('Unknown style'),value:classNames[classNames.length-1]}));index=store.getCount()-1;dropDown.setValue(classNames[classNames.length-1]);if(!defaultClass){store.getAt(0).set('text',this.localize('Remove style'));}}
store.each(function(option){if(store.indexOf(option)!=index&&(','+classNames.join(',')+',').indexOf(','+option.get('value')+',')!=-1){store.removeAt(store.indexOf(option));}
return true;});}
dropDown.setDisabled(!(store.getCount()>1));},buildCssArray:function(editor,dropDownId){this.cssArray=this.parseStyleSheet();if(!this.cssLoaded&&(this.cssParseCount<17)){this.cssTimeout=this.buildCssArray.defer(200,this,[editor,dropDownId]);this.cssParseCount++;}else{this.cssTimeout=null;this.cssLoaded=true;this.cssArray=this.sortCssArray(this.cssArray);this.updateValue(dropDownId);}},parseStyleSheet:function(){var iframe=this.editor._iframe.contentWindow?this.editor._iframe.contentWindow.document:this.editor._iframe.contentDocument;var newCssArray=new Object();this.cssLoaded=true;for(var i=0;i<iframe.styleSheets.length;i++){if(!Ext.isIE){try{newCssArray=this.parseCssRule(iframe.styleSheets[i].cssRules,newCssArray);}catch(e){this.cssLoaded=false;}}else{try{if(iframe.styleSheets[i].imports){newCssArray=this.parseCssIEImport(iframe.styleSheets[i].imports,newCssArray);}
if(iframe.styleSheets[i].rules){newCssArray=this.parseCssRule(iframe.styleSheets[i].rules,newCssArray);}}catch(e){this.cssLoaded=false;}}}
return newCssArray;},parseCssIEImport:function(cssIEImport,cssArray){var newCssArray=new Object();newCssArray=cssArray;for(var i=0;i<cssIEImport.length;i++){if(cssIEImport[i].imports){newCssArray=this.parseCssIEImport(cssIEImport[i].imports,newCssArray);}
if(cssIEImport[i].rules){newCssArray=this.parseCssRule(cssIEImport[i].rules,newCssArray);}}
return newCssArray;},parseCssRule:function(cssRules,cssArray){var newCssArray=new Object();newCssArray=cssArray;for(var rule=0;rule<cssRules.length;rule++){if(cssRules[rule].selectorText){newCssArray=this.parseSelectorText(cssRules[rule].selectorText,newCssArray);}else{if(cssRules[rule].styleSheet){newCssArray=this.parseCssRule(cssRules[rule].styleSheet.cssRules,newCssArray);}
if(cssRules[rule].cssRules){newCssArray=this.parseCssRule(cssRules[rule].cssRules,newCssArray);}}}
return newCssArray;},parseSelectorText:function(selectorText,cssArray){var cssElements=new Array();var cssElement=new Array();var tagName,className;var newCssArray=new Object();newCssArray=cssArray;if(selectorText.search(/:+/)==-1){cssElements=selectorText.split(",");for(var k=0;k<cssElements.length;k++){var s=cssElements[k],pattern=/(\S*)\.(\S+)/,index;while((index=s.search(pattern))>-1){var match=pattern.exec(s.substring(index));s=s.substring(index+match[0].length);tagName=(match[1]&&(match[1]!='*'))?match[1].toLowerCase().trim():"all";className=match[2];if(className&&!HTMLArea.reservedClassNames.test(className)){if(((tagName!="all")&&(!this.tags||!this.tags[tagName]))||((tagName=="all")&&(!this.tags||!this.tags[tagName])&&this.showTagFreeClasses)||(this.tags&&this.tags[tagName]&&this.tags[tagName].allowedClasses&&this.tags[tagName].allowedClasses.test(className))){if(!newCssArray[tagName]){newCssArray[tagName]=new Object();}
if(className){cssName=className;if(HTMLArea.classesLabels&&HTMLArea.classesLabels[className]){cssName=this.prefixLabelWithClassName?(className+" - "+HTMLArea.classesLabels[className]):HTMLArea.classesLabels[className];cssName=this.postfixLabelWithClassName?(cssName+" - "+className):cssName;}}else{className="none";cssName=this.localize("Element style");}
newCssArray[tagName][className]=cssName;}}}}}
return newCssArray;},sortCssArray:function(cssArray){var newCssArray=new Object();for(var tagName in cssArray){if(cssArray.hasOwnProperty(tagName)){newCssArray[tagName]=new Object();var tagArrayKeys=new Array();for(var cssClass in cssArray[tagName]){if(cssArray[tagName].hasOwnProperty(cssClass)){tagArrayKeys.push(cssClass);}}
function compare(a,b){x=cssArray[tagName][a];y=cssArray[tagName][b];return((x<y)?-1:((x>y)?1:0));}
tagArrayKeys=tagArrayKeys.sort(compare);for(var i=0;i<tagArrayKeys.length;++i){newCssArray[tagName][tagArrayKeys[i]]=cssArray[tagName][tagArrayKeys[i]];}}}
return newCssArray;}});