if(typeof(HTMLArea)=='undefined'){Ext.namespace('HTMLArea.util.TYPO3','HTMLArea.util.Tips','HTMLArea.util.Color','Ext.ux.form','Ext.ux.menu','Ext.ux.Toolbar');Ext.apply(HTMLArea,{is_gecko:Ext.isGecko||Ext.isOpera||Ext.isWebKit,is_ff2:Ext.isGecko2,is_ie:Ext.isIE,is_safari:Ext.isWebKit,is_chrome:Ext.isChrome,is_opera:Ext.isOpera,RE_tagName:/(<\/|<)\s*([^ \t\n>]+)/ig,RE_head:/<head>((.|\n)*?)<\/head>/i,RE_body:/<body>((.|\n)*?)<\/body>/i,Reg_body:new RegExp('<\/?(body)[^>]*>','gi'),reservedClassNames:/htmlarea/,RE_email:/([0-9a-z]+([a-z0-9_-]*[0-9a-z])*){1}(\.[0-9a-z]+([a-z0-9_-]*[0-9a-z])*)*@([0-9a-z]+([a-z0-9_-]*[0-9a-z])*\.)+[a-z]{2,9}/i,RE_url:/(([^:/?#]+):\/\/)?(([a-z0-9_]+:[a-z0-9_]+@)?[a-z0-9_-]{2,}(\.[a-z0-9_-]{2,})+\.[a-z]{2,5}(:[0-9]+)?(\/\S+)*)/i,RE_blockTags:/^(body|p|h1|h2|h3|h4|h5|h6|ul|ol|pre|dl|dt|dd|div|noscript|blockquote|form|hr|table|caption|fieldset|address|td|tr|th|li|tbody|thead|tfoot|iframe)$/,RE_closingTags:/^(p|blockquote|a|li|ol|ul|dl|dt|td|th|tr|tbody|thead|tfoot|caption|colgroup|table|div|b|bdo|big|cite|code|del|dfn|em|i|ins|kbd|label|q|samp|small|span|strike|strong|sub|sup|tt|u|var|abbr|acronym|font|center|object|embed|style|script|title|head)$/,RE_noClosingTag:/^(img|br|hr|col|input|area|base|link|meta|param)$/});HTMLArea._appendToLog=function(str){if(HTMLArea.enableDebugMode){var log=document.getElementById('HTMLAreaLog');if(log){log.appendChild(document.createTextNode(str));log.appendChild(document.createElement('br'));}}};HTMLArea.init=function(){Ext.apply(HTMLArea,RTEarea[0]);Ext.applyIf(HTMLArea,{editorSkin:HTMLArea.editorUrl+'skins/default/',editorCSS:HTMLArea.editorUrl+'skins/default/htmlarea.css'});if(!Ext.isString(HTMLArea.editedContentCSS)){HTMLArea.editedContentCSS=HTMLArea.editorSkin+'htmlarea-edited-content.css';}
HTMLArea.isReady=true;HTMLArea._appendToLog("[HTMLArea::init]: Editor url set to: "+HTMLArea.editorUrl);HTMLArea._appendToLog("[HTMLArea::init]: Editor skin CSS set to: "+HTMLArea.editorCSS);HTMLArea._appendToLog("[HTMLArea::init]: Editor content skin CSS set to: "+HTMLArea.editedContentCSS);};HTMLArea.Config=function(editorId){this.editorId=editorId;this.useHTTPS=false;this.useCSS=false;this.enableMozillaExtension=true;this.disableEnterParagraphs=false;this.disableObjectResizing=false;this.removeTrailingBR=false;this.editedContentStyle=HTMLArea.editedContentCSS;this.pageStyle="";this.htmlRemoveTags=null;this.htmlRemoveTagsAndContents=null;this.htmlRemoveComments=false;this.customTags=null;this.baseURL=document.baseURI||document.URL;if(this.baseURL&&this.baseURL.match(/(.*\:\/\/.*\/)[^\/]*/)){this.baseURL=RegExp.$1;}
this.popupURL="popups/";this.documentType='<!DOCTYPE html\r'
+'    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"\r'
+'    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r';this.resizable=TYPO3.settings.textareaResize;this.maxHeight=TYPO3.settings.textareaMaxHeight;this.buttonsConfig={};this.hotKeyList={};this.configDefaults={all:{xtype:'htmlareabutton',disabledClass:'buttonDisabled',textMode:false,selection:false,dialog:false,hidden:false,hideMode:'display'},htmlareabutton:{cls:'button',overCls:'buttonHover',clickEvent:(Ext.isWebKit||Ext.isIE)?'mousedown':'click'},htmlareacombo:{cls:'select',typeAhead:true,lastQuery:'',triggerAction:'all',editable:!Ext.isIE,selectOnFocus:!Ext.isIE,validationEvent:false,validateOnBlur:false,submitValue:false,forceSelection:true,mode:'local',storeRoot:'options',storeFields:[{name:'text'},{name:'value'}],valueField:'value',displayField:'text',labelSeparator:'',hideLabel:true,tpl:'<tpl for="."><div ext:qtip="{value}" style="text-align:left;font-size:11px;" class="x-combo-list-item">{text}</div></tpl>'}};};HTMLArea.Config=Ext.extend(HTMLArea.Config,{registerButton:function(config){config.itemId=config.id;if(Ext.type(this.buttonsConfig[config.id])){HTMLArea._appendToLog('[HTMLArea.Config::registerButton]: A toolbar item with the same Id: '+config.id+' already exists and will be overidden.');}
config=Ext.applyIf(config,this.configDefaults['all']);config=Ext.applyIf(config,this.configDefaults[config.xtype]);switch(config.xtype){case'htmlareacombo':if(config.options){config.store=new Ext.data.ArrayStore({autoDestroy:true,fields:config.storeFields,data:config.options});}else if(config.storeUrl){config.store=new Ext.data.JsonStore({autoDestroy:true,autoLoad:true,root:config.storeRoot,fields:config.storeFields,url:config.storeUrl});}
config.hideLabel=Ext.isEmpty(config.fieldLabel)||Ext.isIE6;config.helpTitle=config.tooltip;break;default:if(!config.iconCls){config.iconCls=config.id;}
break;}
config.cmd=config.id;config.tooltip={title:config.tooltip};this.buttonsConfig[config.id]=config;return true;},registerHotKey:function(hotKeyConfiguration){if(Ext.isDefined(this.hotKeyList[hotKeyConfiguration.id])){HTMLArea._appendToLog('[HTMLArea.Config::registerHotKey]: A hotkey with the same key '+hotKeyConfiguration.id+' already exists and will be overidden.');}
if(Ext.isDefined(hotKeyConfiguration.cmd)&&!Ext.isEmpty(hotKeyConfiguration.cmd)&&Ext.isDefined(this.buttonsConfig[hotKeyConfiguration.cmd])){this.hotKeyList[hotKeyConfiguration.id]=hotKeyConfiguration;HTMLArea._appendToLog('[HTMLArea.Config::registerHotKey]: A hotkey with key '+hotKeyConfiguration.id+' was registered for toolbar item '+hotKeyConfiguration.cmd+'.');return true;}else{HTMLArea._appendToLog('[HTMLArea.Config::registerHotKey]: A hotkey with key '+hotKeyConfiguration.id+' could not be registered because toolbar item with id '+hotKeyConfiguration.cmd+' was not registered.');return false;}},getDocumentType:function(){return this.documentType;}});Ext.ux.HTMLAreaButton=Ext.extend(Ext.Button,{initComponent:function(){Ext.ux.HTMLAreaButton.superclass.initComponent.call(this);this.addEvents('hotkey','context');this.addListener({afterrender:{fn:this.initEventListeners,single:true}});},initEventListeners:function(){this.addListener({hotkey:{fn:this.onHotKey},context:{fn:this.onButtonClick}});this.setHandler(this.onButtonClick,this);this.mon(this.getToolbar(),'update',this.onUpdateToolbar,this);},getEditor:function(){return RTEarea[this.ownerCt.editorId].editor;},getToolbar:function(){return this.ownerCt;},inactive:true,activeClass:'buttonActive',setInactive:function(inactive){this.inactive=inactive;return inactive?this.removeClass(this.activeClass):this.addClass(this.activeClass);},isInContext:function(mode,selectionEmpty,ancestors){var editor=this.getEditor();var inContext=true;if(mode==='wysiwyg'&&this.context){var attributes=[],contexts=[];if(/(.*)\[(.*?)\]/.test(this.context)){contexts=RegExp.$1.split(',');attributes=RegExp.$2.split(',');}else{contexts=this.context.split(',');}
contexts=new RegExp('^('+contexts.join('|')+')$','i');var matchAny=contexts.test('*');Ext.each(ancestors,function(ancestor){inContext=matchAny||contexts.test(ancestor.nodeName);if(inContext){Ext.each(attributes,function(attribute){inContext=eval("ancestor."+attribute);return inContext;});}
return!inContext;});}
return inContext&&(!this.selection||!selectionEmpty);},onButtonClick:function(button,event,key){if(!this.disabled){if(!this.plugins[this.action](this.getEditor(),key||this.itemId)&&event){event.stopEvent();}
if(Ext.isOpera){this.getEditor().focus();}
if(this.dialog){this.setDisabled(true);}else{this.getToolbar().update();}}
return false;},onHotKey:function(key,event){return this.onButtonClick(this,event,key);},onUpdateToolbar:function(mode,selectionEmpty,ancestors,endPointsInSameBlock){this.setDisabled(mode==='textmode'&&!this.textMode);if(!this.disabled){if(!this.noAutoUpdate){this.setDisabled(!this.isInContext(mode,selectionEmpty,ancestors));}
this.plugins['onUpdateToolbar'](this,mode,selectionEmpty,ancestors,endPointsInSameBlock);}}});Ext.reg('htmlareabutton',Ext.ux.HTMLAreaButton);Ext.ux.Toolbar.HTMLAreaToolbarText=Ext.extend(Ext.Toolbar.TextItem,{initComponent:function(){Ext.ux.Toolbar.HTMLAreaToolbarText.superclass.initComponent.call(this);this.addListener({afterrender:{fn:this.initEventListeners,single:true}});},initEventListeners:function(){this.mon(this.getToolbar(),'update',this.onUpdateToolbar,this);},getEditor:function(){return RTEarea[this.ownerCt.editorId].editor;},getToolbar:function(){return this.ownerCt;},onUpdateToolbar:function(mode,selectionEmpty,ancestors,endPointsInSameBlock){this.setDisabled(mode==='textmode'&&!this.textMode);if(!this.disabled){this.plugins['onUpdateToolbar'](this,mode,selectionEmpty,ancestors,endPointsInSameBlock);}}});Ext.reg('htmlareatoolbartext',Ext.ux.Toolbar.HTMLAreaToolbarText);Ext.ux.form.HTMLAreaCombo=Ext.extend(Ext.form.ComboBox,{initComponent:function(){Ext.ux.form.HTMLAreaCombo.superclass.initComponent.call(this);this.addEvents('hotkey');this.addListener({afterrender:{fn:this.initEventListeners,single:true}});},initEventListeners:function(){this.addListener({select:{fn:this.onComboSelect},specialkey:{fn:this.onSpecialKey},hotkey:{fn:this.onHotKey},beforedestroy:{fn:this.onBeforeDestroy,single:true}});this.mon(this.getToolbar(),'update',this.onUpdateToolbar,this);this.mon(this.getToolbar().ownerCt,'frameworkready',this.onFrameworkReady,this);},getEditor:function(){return RTEarea[this.ownerCt.editorId].editor;},getToolbar:function(){return this.ownerCt;},onComboSelect:function(combo,record,index){if(!combo.disabled){var editor=this.getEditor();if(Ext.isIE){editor.focus();if(!Ext.isEmpty(this.savedRange)){editor.selectRange(this.savedRange);this.savedRange=null;}}
this.plugins[this.action](editor,combo,record,index);if(Ext.isIE){editor.focus();this.savedRange=editor._createRange(editor._getSelection());this.triggered=true;}
if(Ext.isOpera){editor.focus();}
this.getToolbar().update();}
return false;},onTriggerClick:function(){Ext.ux.form.HTMLAreaCombo.superclass.onTriggerClick.call(this);if(Ext.isIE){this.triggered=true;this.getEditor().focus();}},onViewClick:function(doFocus){Ext.ux.form.HTMLAreaCombo.superclass.onViewClick.call(this,false);},saveSelection:function(event){var editor=this.getEditor();if(editor.document.hasFocus()){this.savedRange=editor._createRange(editor._getSelection());}},restoreSelection:function(event){if(!Ext.isEmpty(this.savedRange)&&this.triggered){this.getEditor().selectRange(this.savedRange);this.triggered=false;}},onSpecialKey:function(combo,event){if(event.getKey()==event.ENTER){event.stopEvent();}
return false;},onHotKey:function(key){if(!this.disabled){this.plugins.onHotKey(this.getEditor(),key);if(Ext.isOpera){this.getEditor().focus();}
this.getToolbar().update();}
return false;},onUpdateToolbar:function(mode,selectionEmpty,ancestors,endPointsInSameBlock){this.setDisabled(mode==='textmode'&&!this.textMode);if(!this.disabled){this.plugins['onUpdateToolbar'](this,mode,selectionEmpty,ancestors,endPointsInSameBlock);}},onFrameworkReady:function(){var iframe=this.getEditor().iframe;this.mon(Ext.get(iframe.document.documentElement),'click',this.collapse,this);if(Ext.isIE){this.mon(iframe.getEl(),'mouseleave',this.saveSelection,this);this.mon(iframe.getEl(),'focus',this.restoreSelection,this);}},onBeforeDestroy:function(){this.savedRange=null;this.getStore().removeAll();this.getStore().destroy();}});Ext.reg('htmlareacombo',Ext.ux.form.HTMLAreaCombo);HTMLArea.Toolbar=Ext.extend(Ext.Container,{initComponent:function(){HTMLArea.Toolbar.superclass.initComponent.call(this);this.addEvents('update');this.updateLater=new Ext.util.DelayedTask(this.update,this);this.addItems();this.addListener({afterrender:{fn:this.initEventListeners,single:true}});},initEventListeners:function(){this.addListener({beforedestroy:{fn:this.onBeforeDestroy,single:true}});this.mon(this.getEditor(),'editorready',this.update,this,{single:true});},editorId:null,getEditor:function(){return RTEarea[this.editorId].editor;},addItems:function(){var editor=this.getEditor();var firstOnRow=true;var firstInGroup=true;Ext.each(editor.config.toolbar,function(row){if(!firstOnRow){this.add({xtype:'tbspacer',cls:'x-form-clear-left'});}
firstOnRow=true;Ext.each(row,function(group){if(!firstOnRow&&!firstInGroup){this.add({xtype:'tbseparator',cls:'separator'});}
firstInGroup=true;Ext.each(group,function(item){if(item=='space'){this.add({xtype:'tbspacer',cls:'space'});}else{var itemConfig=editor.config.buttonsConfig[item];if(!Ext.isEmpty(itemConfig)){itemConfig.id=this.editorId+'-'+itemConfig.id;this.add(itemConfig);firstInGroup=firstInGroup&&itemConfig.hidden;firstOnRow=firstOnRow&&firstInGroup;}}
return true;},this);return true;},this);return true;},this);this.add({xtype:'tbspacer',cls:'x-form-clear-left'});},getButton:function(buttonId){return this.find('itemId',buttonId)[0];},update:function(){var editor=this.getEditor(),mode=editor.getMode(),selectionEmpty=true,ancestors=null,endPointsInSameBlock=true;if(editor.getMode()==='wysiwyg'){selectionEmpty=editor._selectionEmpty(editor._getSelection());ancestors=editor.getAllAncestors();endPointsInSameBlock=editor.endPointsInSameBlock();}
this.fireEvent('update',mode,selectionEmpty,ancestors,endPointsInSameBlock);},onBeforeDestroy:function(){this.removeAll(true);return true;}});Ext.reg('htmlareatoolbar',HTMLArea.Toolbar);HTMLArea.Iframe=Ext.extend(Ext.BoxComponent,{initComponent:function(){HTMLArea.Iframe.superclass.initComponent.call(this);this.addEvents('iframeready');this.addListener({afterrender:{fn:this.initEventListeners,single:true},beforedestroy:{fn:this.onBeforeDestroy,single:true}});this.config=this.getEditor().config;if(!this.config.showStatusBar){this.addClass('noStatusBar');}},initEventListeners:function(){this.initStyleChangeEventListener();if(Ext.isOpera){this.mon(this.getEl(),'load',this.initializeIframe,this,{single:true});}else{this.initializeIframe();}},initStyleChangeEventListener:function(){if(this.isNested&&!Ext.isWebKit){var options={stopEvent:true};if(Ext.isGecko){options.delay=50;}
Ext.each(this.nestedParentElements.sorted,function(nested){if(!Ext.isGecko){options.target=Ext.get(nested);}
this.mon(Ext.get(nested),Ext.isIE?'propertychange':'DOMAttrModified',this.onNestedShow,this,options);},this);}},editorId:null,getEditor:function(){return RTEarea[this.editorId].editor;},getToolbar:function(){return this.ownerCt.getTopToolbar();},getButton:function(buttonId){return this.getToolbar().getButton(buttonId);},ready:false,onRender:function(ct,position){if(!this.el&&this.autoEl){if(Ext.isString(this.autoEl)){this.el=document.createElement(this.autoEl);}else{this.el=Ext.DomHelper.append(ct,this.autoEl,true);}
if(!this.el.id){this.el.id=this.getId();}}
if(this.resizeEl){this.resizeEl=Ext.get(this.resizeEl);}
if(this.positionEl){this.positionEl=Ext.get(this.positionEl);}},initializeIframe:function(){var iframe=this.getEl().dom;if(!iframe||(!iframe.contentWindow&&!iframe.contentDocument)){this.initializeIframe.defer(50,this);}else if(iframe.contentWindow&&!Ext.isWebKit&&(!iframe.contentWindow.document||!iframe.contentWindow.document.documentElement)){this.initializeIframe.defer(50,this);}else if(Ext.isWebKit&&(!iframe.contentDocument.documentElement||!iframe.contentDocument.body)){this.initializeIframe.defer(50,this);}else{this.document=iframe.contentWindow?iframe.contentWindow.document:iframe.contentDocument;this.getEditor().document=this.document;this.getEditor()._doc=this.document;this.getEditor()._iframe=iframe;this.createHead();this.getStyleSheets();}},createHead:function(){var head=this.document.getElementsByTagName('head')[0];if(!head){head=this.document.createElement('head');this.document.documentElement.appendChild(head);}
if(this.config.baseURL){var base=this.document.getElementsByTagName('base')[0];if(!base){base=this.document.createElement('base');base.href=this.config.baseURL;head.appendChild(base);}
HTMLArea._appendToLog('[HTMLArea.Iframe::createHead]: Iframe baseURL set to: '+base.href);}
var link0=this.document.getElementsByTagName('link')[0];if(!link0){link0=this.document.createElement('link');link0.rel='stylesheet';link0.href=((Ext.isGecko&&navigator.productSub<2010072200&&!/^http(s?):\/{2}/.test(this.config.editedContentStyle))?this.config.baseURL:'')+this.config.editedContentStyle;head.appendChild(link0);HTMLArea._appendToLog('[HTMLArea.Iframe::createHead]: Skin CSS set to: '+link0.href);}
if(this.config.defaultPageStyle){var link=this.document.getElementsByTagName('link')[1];if(!link){link=this.document.createElement('link');link.rel='stylesheet';link.href=((Ext.isGecko&&navigator.productSub<2010072200&&!/^https?:\/{2}/.test(this.config.defaultPageStyle))?this.config.baseURL:'')+this.config.defaultPageStyle;head.appendChild(link);}
HTMLArea._appendToLog('[HTMLArea.Iframe::createHead]: Override CSS set to: '+link.href);}
if(this.config.pageStyle){var link=this.document.getElementsByTagName('link')[2];if(!link){link=this.document.createElement('link');link.rel='stylesheet';link.href=((Ext.isGecko&&navigator.productSub<2010072200&&!/^https?:\/{2}/.test(this.config.pageStyle))?this.config.baseURL:'')+this.config.pageStyle;head.appendChild(link);}
HTMLArea._appendToLog('[HTMLArea.Iframe::createHead]: Content CSS set to: '+link.href);}
HTMLArea._appendToLog('[HTMLArea.Iframe::createHead]: Editor iframe document head successfully built.');},getStyleSheets:function(){var stylesAreLoaded=true;var errorText='';var rules;if(Ext.isOpera){if(this.document.readyState!='complete'){stylesAreLoaded=false;errorText='Document.readyState not complete';}}else{if(Ext.isIE){try{rules=this.document.styleSheets[0].rules;}catch(e){stylesAreLoaded=false;errorText=e;}}else{try{rules=this.document.styleSheets[0].cssRules;}catch(e){stylesAreLoaded=false;errorText=e;}}
if(stylesAreLoaded){Ext.each(this.document.styleSheets,function(styleSheet){if(Ext.isIE){try{rules=styleSheet.rules;}catch(e){stylesAreLoaded=false;errorText=e;return false;}
try{rules=styleSheet.imports;}catch(e){stylesAreLoaded=false;errorText=e;return false;}}else{try{rules=styleSheet.cssRules;}catch(e){stylesAreLoaded=false;errorText=e;return false;}}});}}
if(!stylesAreLoaded){this.getStyleSheets.defer(100,this);HTMLArea._appendToLog('[HTMLArea.Iframe::getStyleSheets]: Stylesheets not yet loaded ('+errorText+'). Retrying...');if(/Security/i.test(errorText)){HTMLArea._appendToLog('ERROR [HTMLArea.Iframe::getStyleSheets]: A security error occurred. Make sure all stylesheets are accessed from the same domain/subdomain and using the same protocol as the current script.');}}else{HTMLArea._appendToLog('[HTMLArea.Iframe::getStyleSheets]: Stylesheets successfully accessed.');Ext.get(this.document.body).addClass('htmlarea-content-body');if(!Ext.isOpera){this.startListening();}
this.hide();this.ready=true;this.fireEvent('iframeready');}},focus:function(){try{if(Ext.isWebKit){this.getEl().dom.focus();}else{this.getEl().dom.contentWindow.focus();}}catch(e){}},isNested:false,nestedParentElements:{},setDesignMode:function(on){if(on){if(!Ext.isIE){if(Ext.isGecko){if(!this.isNested||HTMLArea.util.TYPO3.allElementsAreDisplayed(this.nestedParentElements.sorted)){this.document.designMode='on';this.setOptions();}}else{this.document.designMode='on';this.setOptions();}}
if(Ext.isIE||Ext.isWebKit){this.document.body.contentEditable=true;}}else{if(!Ext.isIE){this.document.designMode='off';}
if(Ext.isIE||Ext.isWebKit){this.document.body.contentEditable=false;}}},setOptions:function(){if(!Ext.isIE){try{if(this.document.queryCommandEnabled('insertBrOnReturn')){this.document.execCommand('insertBrOnReturn',false,this.config.disableEnterParagraphs);}
if(this.document.queryCommandEnabled('styleWithCSS')){this.document.execCommand('styleWithCSS',false,this.config.useCSS);}else if(Ext.isGecko&&this.document.queryCommandEnabled('useCSS')){this.document.execCommand('useCSS',false,!this.config.useCSS);}
if(Ext.isGecko){if(this.document.queryCommandEnabled('enableObjectResizing')){this.document.execCommand('enableObjectResizing',false,!this.config.disableObjectResizing);}
if(this.document.queryCommandEnabled('enableInlineTableEditing')){this.document.execCommand('enableInlineTableEditing',false,(this.config.buttons.table&&this.config.buttons.table.enableHandles)?true:false);}}}catch(e){}}},onNestedShow:function(event,target){var styleEvent=true;if((Ext.isGecko&&navigator.productSub>2007112700)||Ext.isOpera){styleEvent=(event.browserEvent.attrName=='style');}else if(Ext.isIE){styleEvent=(event.browserEvent.propertyName=='style.display');}
if(styleEvent&&this.nestedParentElements.sorted.indexOf(target.id)!=-1&&(target.style.display==''||target.style.display=='block')){if(HTMLArea.util.TYPO3.allElementsAreDisplayed(this.nestedParentElements.sorted)){if(this.getEditor().getMode()==='wysiwyg'){if(Ext.isGecko){this.setDesignMode(true);}
this.fireEvent('show');}else{this.ownerCt.textAreaContainer.fireEvent('show');}
this.getToolbar().update();return false;}}},getHTML:function(){return HTMLArea.getHTML(this.document.body,false,this.getEditor());},startListening:function(){this.keyMap=new Ext.KeyMap(Ext.get(this.document.documentElement),[],(Ext.isIE||Ext.isWebKit)?'keydown':'keypress');this.keyMap.addBinding([{key:[Ext.EventObject.DOWN,Ext.EventObject.UP,Ext.EventObject.LEFT,Ext.EventObject.RIGHT],alt:false,handler:this.onArrow,scope:this},{key:Ext.EventObject.TAB,ctrl:false,alt:false,handler:this.onTab,scope:this},{key:Ext.EventObject.SPACE,ctrl:true,shift:false,alt:false,handler:this.onCtrlSpace,scope:this}]);if(Ext.isGecko||Ext.isIE){this.keyMap.addBinding({key:[Ext.EventObject.BACKSPACE,Ext.EventObject.DELETE],alt:false,handler:this.onBackSpace,scope:this});}
if(!Ext.isIE&&!this.config.disableEnterParagraphs){this.keyMap.addBinding({key:Ext.EventObject.ENTER,shift:false,handler:this.onEnter,scope:this});}
if(Ext.isWebKit){this.keyMap.addBinding({key:Ext.EventObject.ENTER,alt:false,handler:this.onWebKitEnter,scope:this});}
var hotKeys='';Ext.iterate(this.config.hotKeyList,function(key){if(key.length==1){hotKeys+=key.toUpperCase();}});this.hotKeyMap=new Ext.KeyMap(Ext.get(this.document.documentElement));if(!Ext.isEmpty(hotKeys)){this.hotKeyMap.addBinding({key:hotKeys,ctrl:true,shift:false,alt:false,handler:this.onHotKey,scope:this});}
this.mon(Ext.get(this.document.documentElement),(Ext.isIE||Ext.isWebKit)?'keydown':'keypress',this.onAnyKey,this);this.mon(Ext.get(this.document.documentElement),'mouseup',this.onMouse,this);this.mon(Ext.get(this.document.documentElement),'click',this.onMouse,this);this.mon(Ext.get(this.document.documentElement),Ext.isWebKit?'dragend':'drop',this.onDrop,this);},onAnyKey:function(event){if(this.inhibitKeyboardInput(event)){return false;}
if(this.getEditor().hasPluginWithOnKeyPressHandler){var letBubble=true;Ext.iterate(this.getEditor().plugins,function(pluginId){var plugin=this.getEditor().getPlugin(pluginId);if(Ext.isFunction(plugin.onKeyPress)){if(!plugin.onKeyPress(event.browserEvent)){event.stopEvent();letBubble=false;}}
return letBubble;},this);if(!letBubble){return letBubble;}}
if(!event.altKey&&!event.ctrlKey){if(!Ext.isIE&&(event.getKey()!=Ext.EventObject.ENTER||(event.shiftKey&&!Ext.isWebKit))){this.getEditor()._detectURL(event);}
if(Ext.isMac&&event.browserEvent.charCode==160){return this.onOptionSpace(event.browserEvent.charCode,event);}}
return true;},inhibitKeyboardInput:function(event){if(this.getEditor().inhibitKeyboardInput){event.stopEvent();return true;}else{return false;}},onMouse:function(){this.getToolbar().updateLater.delay(100);return true;},onDrop:function(event){if(Ext.isWebKit){this.getEditor().cleanAppleStyleSpans.defer(50,this.getEditor(),[this.getEditor().document.body]);}
this.getToolbar().updateLater.delay(100);},onArrow:function(){this.getToolbar().updateLater.delay(100);return true;},onTab:function(key,event){if(this.inhibitKeyboardInput(event)){return false;}
var keyName=(event.shiftKey?'SHIFT-':'')+'TAB';if(this.config.hotKeyList[keyName]&&this.config.hotKeyList[keyName].cmd){var button=this.getButton(this.config.hotKeyList[keyName].cmd);if(button){event.stopEvent();button.fireEvent('hotkey',keyName,event);return false;}}
return true;},onBackSpace:function(key,event){if(this.inhibitKeyboardInput(event)){return false;}
if((!Ext.isIE&&!event.shiftKey)||Ext.isIE){if(this.getEditor()._checkBackspace()){event.stopEvent();}}
this.getToolbar().updateLater.delay(200);return false;},onEnter:function(key,event){if(this.inhibitKeyboardInput(event)){return false;}
this.getEditor()._detectURL(event);if(this.getEditor()._checkInsertP()){event.stopEvent();}
this.getToolbar().updateLater.delay(200);return false;},onWebKitEnter:function(key,event){if(this.inhibitKeyboardInput(event)){return false;}
if(event.shiftKey||this.config.disableEnterParagraphs){var editor=this.getEditor();editor._detectURL(event);if(Ext.isSafari){var brNode=editor.document.createElement('br');editor.insertNodeAtSelection(brNode);brNode.parentNode.normalize();if(editor._unlinkOnUndo){brNode=brNode.parentNode.parentNode.insertBefore(brNode,brNode.parentNode.nextSibling);}
if(!brNode.nextSibling||!/\S+/i.test(brNode.nextSibling.textContent)){var secondBrNode=editor.document.createElement('br');secondBrNode=brNode.parentNode.appendChild(secondBrNode);}
editor.selectNode(brNode,false);event.stopEvent();}}
this.getToolbar().updateLater.delay(200);return false;},onCtrlSpace:function(key,event){if(this.inhibitKeyboardInput(event)){return false;}
this.getEditor().insertHTML('&nbsp;');event.stopEvent();return false;},onOptionSpace:function(key,event){if(this.inhibitKeyboardInput(event)){return false;}
this.getEditor().insertHTML('&nbsp;');event.stopEvent();return false;},onHotKey:function(key,event){if(this.inhibitKeyboardInput(event)){return false;}
var hotKey=String.fromCharCode(key).toLowerCase();this.getButton(this.config.hotKeyList[hotKey].cmd).fireEvent('hotkey',hotKey,event);return false;},onBeforeDestroy:function(){Ext.each(this.keyMap.bindings,function(binding,index){this.keyMap.bindings[index]=null;},this);this.keyMap.handleKeyDown=null;Ext.each(this.hotKeyMap.bindings,function(binding,index){this.hotKeyMap.bindings[index]=null;},this);this.hotKeyMap.handleKeyDown=null;this.keyMap.disable();this.hotKeyMap.disable();Ext.get(this.document.body).purgeAllListeners();Ext.get(this.document.body).dom=null;Ext.get(this.document.documentElement).purgeAllListeners();Ext.get(this.document.documentElement).dom=null;this.document=null;this.getEditor().document=null;this.getEditor()._doc=null;this.getEditor()._iframe=null;Ext.each(this.nestedParentElements.sorted,function(nested){Ext.get(nested).purgeAllListeners();Ext.get(nested).dom=null;});Ext.destroy(this.autoEl,this.el,this.resizeEl,this.positionEl);return true;}});Ext.reg('htmlareaiframe',HTMLArea.Iframe);Ext.ux.StatusBar=Ext.extend(Ext.Toolbar,{cls:'x-statusbar',busyIconCls:'x-status-busy',busyText:'Loading...',autoClear:5000,emptyText:'&nbsp;',activeThreadId:0,initComponent:function(){if(this.statusAlign=='right'){this.cls+=' x-status-right';}
Ext.ux.StatusBar.superclass.initComponent.call(this);},afterRender:function(){Ext.ux.StatusBar.superclass.afterRender.call(this);var right=this.statusAlign=='right';this.currIconCls=this.iconCls||this.defaultIconCls;this.statusEl=new Ext.Toolbar.TextItem({cls:'x-status-text '+(this.currIconCls||''),text:this.text||this.defaultText||''});if(right){this.add('->');this.add(this.statusEl);}else{this.insert(0,this.statusEl);this.insert(1,'->');}
this.doLayout();},setStatus:function(o){o=o||{};if(typeof o=='string'){o={text:o};}
if(o.text!==undefined){this.setText(o.text);}
if(o.iconCls!==undefined){this.setIcon(o.iconCls);}
if(o.clear){var c=o.clear,wait=this.autoClear,defaults={useDefaults:true,anim:true};if(typeof c=='object'){c=Ext.applyIf(c,defaults);if(c.wait){wait=c.wait;}}else if(typeof c=='number'){wait=c;c=defaults;}else if(typeof c=='boolean'){c=defaults;}
c.threadId=this.activeThreadId;this.clearStatus.defer(wait,this,[c]);}
return this;},clearStatus:function(o){o=o||{};if(o.threadId&&o.threadId!==this.activeThreadId){return this;}
var text=o.useDefaults?this.defaultText:this.emptyText,iconCls=o.useDefaults?(this.defaultIconCls?this.defaultIconCls:''):'';if(o.anim){this.statusEl.el.fadeOut({remove:false,useDisplay:true,scope:this,callback:function(){this.setStatus({text:text,iconCls:iconCls});this.statusEl.el.show();}});}else{this.statusEl.hide();this.setStatus({text:text,iconCls:iconCls});this.statusEl.show();}
return this;},setText:function(text){this.activeThreadId++;this.text=text||'';if(this.rendered){this.statusEl.setText(this.text);}
return this;},getText:function(){return this.text;},setIcon:function(cls){this.activeThreadId++;cls=cls||'';if(this.rendered){if(this.currIconCls){this.statusEl.removeClass(this.currIconCls);this.currIconCls=null;}
if(cls.length>0){this.statusEl.addClass(cls);this.currIconCls=cls;}}else{this.currIconCls=cls;}
return this;},showBusy:function(o){if(typeof o=='string'){o={text:o};}
o=Ext.applyIf(o||{},{text:this.busyText,iconCls:this.busyIconCls});return this.setStatus(o);}});Ext.reg('statusbar',Ext.ux.StatusBar);HTMLArea.StatusBar=Ext.extend(Ext.Container,{initComponent:function(){HTMLArea.StatusBar.superclass.initComponent.call(this);this.addListener({render:{fn:this.addComponents,single:true},afterrender:{fn:this.initEventListeners,single:true}});},initEventListeners:function(){this.addListener({beforedestroy:{fn:this.onBeforeDestroy,single:true}});this.mon(this.ownerCt.toolbar,'update',this.onUpdateToolbar,this);this.mon(this.getEditor(),'modeChange',this.onModeChange,this);},editorId:null,getEditor:function(){return RTEarea[this.editorId].editor;},addComponents:function(){this.statusBarTree=Ext.DomHelper.append(this.getEl(),{id:this.editorId+'-statusBarTree',tag:'span',cls:'statusBarTree',html:HTMLArea.I18N.msg['Path']+': '},true).setVisibilityMode(Ext.Element.DISPLAY).setVisible(true);this.statusBarTextMode=Ext.DomHelper.append(this.getEl(),{id:this.editorId+'-statusBarTextMode',tag:'span',cls:'statusBarTextMode',html:HTMLArea.I18N.msg['TEXT_MODE']},true).setVisibilityMode(Ext.Element.DISPLAY).setVisible(false);},clear:function(){this.statusBarTree.removeAllListeners();Ext.each(this.statusBarTree.query('a'),function(node){Ext.QuickTips.unregister(node);Ext.get(node).dom.ancestor=null;Ext.destroy(node);});this.statusBarTree.update('');this.setSelection(null);},noUpdate:false,onUpdateToolbar:function(mode,selectionEmpty,ancestors,endPointsInSameBlock){if(mode==='wysiwyg'&&!this.noUpdate){var text,language,languageObject=this.getEditor().getPlugin('Language'),classes=new Array(),classText;this.clear();var path=Ext.DomHelper.append(this.statusBarTree,{tag:'span',html:HTMLArea.I18N.msg['Path']+': '},true);Ext.each(ancestors,function(ancestor,index){if(!ancestor){return true;}
text=ancestor.nodeName.toLowerCase();if(ancestor.id&&text!=='body'&&ancestor.id.substr(0,7)!=='ext-gen'){text+='#'+ancestor.id;}
if(languageObject&&languageObject.getLanguageAttribute){language=languageObject.getLanguageAttribute(ancestor);if(language!='none'){text+='['+language+']';}}
if(ancestor.className){classText='';classes=ancestor.className.trim().split(' ');for(var j=0,n=classes.length;j<n;++j){if(!HTMLArea.reservedClassNames.test(classes[j])){classText+='.'+classes[j];}}
text+=classText;}
var element=Ext.DomHelper.insertAfter(path,{tag:'a',href:'#','ext:qtitle':HTMLArea.I18N.dialogs['statusBarStyle'],'ext:qtip':ancestor.style.cssText.split(';').join('<br />'),html:text},true);element.dom.ancestor=ancestor;if(Ext.isIE){element.on('click',this.onClick,this);}else{element.on('mousedown',this.onMouseDown,this);}
if(!Ext.isOpera){element.on('contextmenu',this.onContextMenu,this);}
if(index){Ext.DomHelper.insertAfter(element,{tag:'span',html:String.fromCharCode(0xbb)});}},this);}
this.noUpdate=false;},onModeChange:function(mode){switch(mode){case'wysiwyg':this.statusBarTextMode.setVisible(false);this.statusBarTree.setVisible(true);break;case'textmode':default:this.statusBarTree.setVisible(false);this.statusBarTextMode.setVisible(true);break;}},selected:null,getSelection:function(){return this.selected;},setSelection:function(element){this.selected=element?element:null;},selectElement:function(element){var editor=this.getEditor();element.blur();if(!Ext.isIE){if(/^(img)$/i.test(element.ancestor.nodeName)){editor.selectNode(element.ancestor);}else{editor.selectNodeContents(element.ancestor);}}else{if(/^(img|table)$/i.test(element.ancestor.nodeName)){var range=editor.document.body.createControlRange();range.addElement(element.ancestor);range.select();}else{editor.selectNode(element.ancestor);}}
this.setSelection(element.ancestor);this.noUpdate=true;editor.toolbar.update();},onClick:function(event,element){this.selectElement(element);event.stopEvent();return false;},onMouseDown:function(event,element){this.selectElement(element);if(Ext.isIE){return true;}else{event.stopEvent();return false;}},onContextMenu:function(event,target){this.selectElement(target);return this.getEditor().getPlugin('ContextMenu')?this.getEditor().getPlugin('ContextMenu').show(event,target.ancestor):false;},onBeforeDestroy:function(){this.clear();this.removeAll(true);Ext.destroy(this.statusBarTree,this.statusBarTextMode);return true;}});Ext.reg('htmlareastatusbar',HTMLArea.StatusBar);HTMLArea.Framework=Ext.extend(Ext.Panel,{initComponent:function(){HTMLArea.Framework.superclass.initComponent.call(this);this.toolbar=this.getTopToolbar();this.statusBar=this.getBottomToolbar();this.iframe=this.getComponent('iframe');this.textAreaContainer=this.getComponent('textAreaContainer');this.addEvents('frameworkready');this.addListener({afterrender:{fn:this.initEventListeners,single:true}});if(!this.isNested||HTMLArea.util.TYPO3.allElementsAreDisplayed(this.nestedParentElements.sorted)){this.render(this.textArea.parent(),this.textArea.id);}else{var parentElements=[].concat(this.nestedParentElements.sorted);HTMLArea.util.TYPO3.accessParentElements(parentElements,'args[0].render(args[0].textArea.parent(), args[0].textArea.id)',[this]);}},initEventListeners:function(){this.mon(this.iframe,'iframeready',this.onIframeReady,this,{single:true});this.makeResizable();this.mon(this.textAreaContainer,'show',this.resizable?this.onTextAreaShow:this.onWindowResize,this);this.mon(this.iframe,'show',this.resizable?this.onIframeShow:this.onWindowResize,this);Ext.EventManager.onWindowResize(this.onWindowResize,this);var form=this.textArea.dom.form;if(form){if(Ext.isFunction(form.onreset)){if(typeof(form.htmlAreaPreviousOnReset)=='undefined'){form.htmlAreaPreviousOnReset=[];}
form.htmlAreaPreviousOnReset.push(form.onreset);}
this.mon(Ext.get(form),'reset',this.onReset,this);}
this.addListener({resize:{fn:this.onFrameworkResize},beforedestroy:{fn:this.onBeforeDestroy,single:true}});},editorId:null,getEditor:function(){return RTEarea[this.editorId].editor;},isNested:false,nestedParentElements:{},ready:false,nestedParentElements:{},resizable:false,maxHeight:2000,textAreaInitialSize:{width:0,contextWidth:0,height:0},doLayout:function(){if(!this.isNested||HTMLArea.util.TYPO3.allElementsAreDisplayed(this.nestedParentElements.sorted)){HTMLArea.Framework.superclass.doLayout.call(this);}else{var parentElements=[].concat(this.nestedParentElements.sorted);HTMLArea.util.TYPO3.accessParentElements(parentElements,'HTMLArea.Framework.superclass.doLayout.call(args[0])',[this]);}},makeResizable:function(){if(this.resizable){this.addClass('resizable');this.resizer=new Ext.Resizable(this.getEl(),{minWidth:300,maxHeight:this.maxHeight,dynamic:false});this.resizer.on('resize',this.onHtmlAreaResize,this);}},onHtmlAreaResize:function(resizer,width,height,event){this.setWidth(width);this.iframe.setHeight(this.getInnerHeight());this.textArea.setSize(this.getInnerWidth(),this.getInnerHeight());},onWindowResize:function(width,height){if(!this.isNested||HTMLArea.util.TYPO3.allElementsAreDisplayed(this.nestedParentElements.sorted)){this.resizeFramework(width,height);}else{var parentElements=[].concat(this.nestedParentElements.sorted);HTMLArea.util.TYPO3.accessParentElements(parentElements,'args[0].resizeFramework(args[1], args[2])',[this,width,height]);}},resizeFramework:function(width,height){var frameworkHeight=parseInt(this.textAreaInitialSize.height);if(this.textAreaInitialSize.width.indexOf('%')===-1){var frameworkWidth=parseInt(this.textAreaInitialSize.width)-this.getFrameWidth();}else{if(Ext.isNumber(width)){var frameworkWidth=parseInt(((width-this.textAreaInitialSize.wizardsWidth-(this.fullScreen?10:Ext.getScrollBarWidth())-this.getBox().x-15)*parseInt(this.textAreaInitialSize.width))/100);}else{var frameworkWidth=parseInt(((HTMLArea.util.TYPO3.getWindowSize().width-this.textAreaInitialSize.wizardsWidth-(this.fullScreen?10:Ext.getScrollBarWidth())-this.getBox().x-15)*parseInt(this.textAreaInitialSize.width))/100);}}
if(this.resizable){this.resizer.resizeTo(frameworkWidth,frameworkHeight);}else{this.setSize(frameworkWidth,frameworkHeight);}},onFrameworkResize:function(){this.iframe.setSize(this.getInnerWidth(),this.getInnerHeight());this.textArea.setSize(this.getInnerWidth(),this.getInnerHeight());},onTextAreaShow:function(){this.iframe.setHeight(this.getInnerHeight());this.textArea.setHeight(this.getInnerHeight());},onIframeShow:function(){if(this.getInnerHeight()<=0){this.onWindowResize();}else{this.iframe.setHeight(this.getInnerHeight());this.textArea.setHeight(this.getInnerHeight());}},onIframeReady:function(){this.ready=this.toolbar.rendered&&this.statusBar.rendered&&this.textAreaContainer.rendered;if(this.ready){this.textAreaContainer.show();if(!this.getEditor().config.showStatusBar){this.statusBar.hide();}
this.onWindowResize();this.fireEvent('frameworkready');}else{this.onIframeReady.defer(50,this);}},onReset:function(event){this.getEditor().setHTML(this.textArea.getValue());this.toolbar.update();var htmlAreaPreviousOnReset=event.getTarget().dom.htmlAreaPreviousOnReset;if(typeof(htmlAreaPreviousOnReset)!='undefined'){Ext.each(htmlAreaPreviousOnReset,function(onReset){onReset();return true;});}},onBeforeDestroy:function(){Ext.EventManager.removeResizeListener(this.onWindowResize,this);var form=this.textArea.dom.form;if(form){form.htmlAreaPreviousOnReset=null;Ext.get(form).dom=null;}
Ext.getBody().dom=null;this.toolbar.destroy();this.statusBar.destroy();this.removeAll(true);if(this.resizable){this.resizer.destroy();}
return true;}});Ext.reg('htmlareaframework',HTMLArea.Framework);HTMLArea.Editor=Ext.extend(Ext.util.Observable,{constructor:function(config){HTMLArea.Editor.superclass.constructor.call(this,{});this.config=config;this.editorId=this.config.editorId;RTEarea[this.editorId].editor=this;this.textArea=Ext.get(this.config.id);this.textAreaInitialSize={width:this.config.RTEWidthOverride?this.config.RTEWidthOverride:this.textArea.getStyle('width'),height:this.config.fullScreen?HTMLArea.util.TYPO3.getWindowSize().height-20:this.textArea.getStyle('height'),wizardsWidth:0};this.nestedParentElements={all:this.config.tceformsNested,sorted:HTMLArea.util.TYPO3.simplifyNested(this.config.tceformsNested)};this.isNested=!Ext.isEmpty(this.nestedParentElements.sorted);if(Ext.get('typo3-docheader')){this.wizards=this.textArea.parent().parent().next();if(this.wizards){if(!this.isNested||HTMLArea.util.TYPO3.allElementsAreDisplayed(this.nestedParentElements.sorted)){this.textAreaInitialSize.wizardsWidth=this.wizards.getWidth();}else{var parentElements=[].concat(this.nestedParentElements.sorted);this.textAreaInitialSize.wizardsWidth=HTMLArea.util.TYPO3.accessParentElements(parentElements,'args[0].getWidth()',[this.wizards]);}
this.wizards.hide();}}
this.plugins={};Ext.iterate(this.config.plugin,function(plugin){if(this.config.plugin[plugin]){this.registerPlugin(plugin);}},this);this.inhibitKeyboardInput=false;this.addEvents('editorready','modeChange','beforedestroy');},ready:false,mode:'textmode',generate:function(){this.htmlArea=new HTMLArea.Framework({id:this.editorId+'-htmlArea',layout:'anchor',baseCls:'htmlarea',editorId:this.editorId,textArea:this.textArea,textAreaInitialSize:this.textAreaInitialSize,fullScreen:this.config.fullScreen,resizable:this.config.resizable,maxHeight:this.config.maxHeight,isNested:this.isNested,nestedParentElements:this.nestedParentElements,tbar:{xtype:'htmlareatoolbar',id:this.editorId+'-toolbar',anchor:'100%',layout:'form',cls:'toolbar',editorId:this.editorId},items:[{xtype:'htmlareaiframe',itemId:'iframe',anchor:'100%',width:(this.textAreaInitialSize.width.indexOf('%')===-1)?parseInt(this.textAreaInitialSize.width):300,height:parseInt(this.textAreaInitialSize.height),autoEl:{id:this.editorId+'-iframe',tag:'iframe',cls:'editorIframe',src:Ext.isGecko?'javascript:void(0);':HTMLArea.editorUrl+'popups/blank.html'},isNested:this.isNested,nestedParentElements:this.nestedParentElements,editorId:this.editorId},{xtype:'box',itemId:'textAreaContainer',anchor:'100%',width:(this.textAreaInitialSize.width.indexOf('%')===-1)?parseInt(this.textAreaInitialSize.width):300,listeners:{afterrender:{fn:function(textAreaContainer){this.originalParent=this.textArea.parent().dom;textAreaContainer.getEl().appendChild(this.textArea);},single:true,scope:this},beforedestroy:{fn:function(textAreaContainer){this.originalParent.appendChild(this.textArea.dom);return true;},single:true,scope:this}}}],bbar:{xtype:'htmlareastatusbar',anchor:'100%',cls:'statusBar',editorId:this.editorId}});this.toolbar=this.htmlArea.getTopToolbar();this.statusBar=this.htmlArea.getBottomToolbar();this.iframe=this.htmlArea.getComponent('iframe');this.textAreaContainer=this.htmlArea.getComponent('textAreaContainer');this.relayEvents(this.htmlArea,['frameworkready']);this.on('frameworkready',this.onFrameworkReady,this,{single:true});},onFrameworkReady:function(){this.setMode('wysiwyg');this.initEventsListening();this.generatePlugins();this.show();if(this.wizards){this.wizards.show();}
Ext.iterate(RTEarea,function(editorId,RTE){if(!Ext.isDefined(RTE.editor)||(RTE.editor.isNested&&!HTMLArea.util.TYPO3.allElementsAreDisplayed(RTE.editor.nestedParentElements.sorted))){return true;}else{RTE.editor.focus();return false;}},this);this.ready=true;this.fireEvent('editorready');HTMLArea._appendToLog('[HTMLArea.Editor::start]: Editor ready.');},setMode:function(mode){switch(mode){case'textmode':this.textArea.set({value:this.getHTML()},false);this.iframe.setDesignMode(false);this.iframe.hide();this.textAreaContainer.show();this.mode=mode;break;case'wysiwyg':try{this.document.body.innerHTML=this.getHTML();}catch(e){HTMLArea._appendToLog('[HTMLArea.Editor::setMode]: The HTML document is not well-formed.');alert(HTMLArea.I18N.msg['HTML-document-not-well-formed']);break;}
this.textAreaContainer.hide();this.iframe.show();this.iframe.setDesignMode(true);this.mode=mode;break;}
this.fireEvent('modeChange',this.mode);this.focus();Ext.iterate(this.plugins,function(pluginId){this.getPlugin(pluginId).onMode(this.mode);},this);},getMode:function(){return this.mode;},getHTML:function(){switch(this.mode){case'wysiwyg':return this.iframe.getHTML();case'textmode':return this.textArea.getValue();default:return'';}},getInnerHTML:function(){switch(this.mode){case'wysiwyg':return this.document.body.innerHTML;case'textmode':return this.textArea.getValue();default:return'';}},setHTML:function(html){switch(this.mode){case'wysiwyg':this.document.body.innerHTML=html;break;case'textmode':this.textArea.set({value:html},false);;break;}},registerPlugin:function(pluginName){var plugin=null;if(Ext.isString(pluginName)){try{plugin=eval(pluginName);}catch(e){try{plugin=eval('HTMLArea.'+pluginName);}catch(error){HTMLArea._appendToLog('ERROR [HTMLArea.Editor::registerPlugin]: Cannot register invalid plugin: '+error);return false;}}}
if(!Ext.isFunction(plugin)){HTMLArea._appendToLog('ERROR [HTMLArea.Editor::registerPlugin]: Cannot register undefined plugin.');return false;}
var pluginInstance=new plugin(this,pluginName);if(pluginInstance){var pluginInformation=pluginInstance.getPluginInformation();pluginInformation.instance=pluginInstance;this.plugins[pluginName]=pluginInformation;HTMLArea._appendToLog('[HTMLArea.Editor::registerPlugin]: Plugin '+pluginName+' was successfully registered.');return true;}else{HTMLArea._appendToLog("ERROR [HTMLArea.Editor::registerPlugin]: Can't register plugin "+pluginName+'.');return false;}},generatePlugins:function(){this.hasPluginWithOnKeyPressHandler=false;Ext.iterate(this.plugins,function(pluginId){var plugin=this.getPlugin(pluginId);plugin.onGenerate();if(Ext.isFunction(plugin.onKeyPress)){this.hasPluginWithOnKeyPressHandler=true;HTMLArea._appendToLog('[HTMLArea.Editor::generatePlugins]: Deprecated use of onKeyPress function by plugin '+pluginId+'. Use keyMap instead.');}},this);HTMLArea._appendToLog('[HTMLArea.Editor::generatePlugins]: All plugins successfully generated.');},getPlugin:function(pluginName){return(this.plugins[pluginName]?this.plugins[pluginName].instance:null);},unRegisterPlugin:function(pluginName){delete this.plugins[pluginName].instance;delete this.plugins[pluginName];},focus:function(){switch(this.getMode()){case'wysiwyg':this.iframe.focus();break;case'textmode':this.textArea.focus();break;}},initEventsListening:function(){if(Ext.isOpera){this.iframe.startListening();}
var iframe=this.iframe.getEl().dom;Ext.EventManager.on(iframe.contentWindow?iframe.contentWindow:iframe.contentDocument,'unload',this.onUnload,this,{single:true});},show:function(){document.getElementById('pleasewait'+this.editorId).style.display='none';document.getElementById('editorWrap'+this.editorId).style.visibility='visible';},onUnload:function(event){if(this.ready){this.textArea.set({value:this.getHTML()},false);}
this.fireEvent('beforedestroy');Ext.TaskMgr.stopAll();this.htmlArea.destroy();Ext.iterate(this.plugins,function(pluginId){this.unRegisterPlugin(pluginId);},this);this.purgeListeners();if(this.wizards){this.wizards.dom=null;this.textArea.parent().parent().dom=null;this.textArea.parent().dom=null;}
this.textArea.dom=null;RTEarea[this.editorId].editor=null;}});HTMLArea.util.TYPO3=function(){return{simplifyNested:function(nested){var i,type,level,elementId,max,simplifiedNested=[],elementIdSuffix={tab:'-DIV',inline:'_fields',flex:'-content'};if(nested&&nested.length){if(nested[0][0]=='inline'){nested=inline.findContinuedNestedLevel(nested,nested[0][1]);}
for(i=0,max=nested.length;i<max;i++){type=nested[i][0];level=nested[i][1];elementId=level+elementIdSuffix[type];if(Ext.get(elementId)){simplifiedNested.push(elementId);}}}
return simplifiedNested;},accessParentElements:function(parentElements,callbackFunc,args){var result={};if(parentElements.length){var currentElement=parentElements.pop();currentElement=Ext.get(currentElement);var actionRequired=(currentElement.getStyle('display')=='none');if(actionRequired){var originalStyles=currentElement.getStyles('visibility','position','top','display');currentElement.setStyle({visibility:'hidden',position:'absolute',top:'-10000px',display:''});}
result=this.accessParentElements(parentElements,callbackFunc,args);if(actionRequired){currentElement.setStyle(originalStyles);}}else{result=eval(callbackFunc);}
return result;},allElementsAreDisplayed:function(elements){var allDisplayed=true;Ext.each(elements,function(element){allDisplayed=Ext.get(element).getStyle('display')!='none';return allDisplayed;});return allDisplayed;},getWindowSize:function(){if(Ext.isIE){var size=Ext.getBody().getSize();}else{var size={width:window.innerWidth,height:window.innerHeight};}
var docHeader=Ext.get('typo3-docheader');if(docHeader){size.height-=docHeader.getHeight();docHeader.dom=null;}
return size;}}}();HTMLArea.loadStyle=function(style,plugin,url){if(typeof(url)=="undefined"){var url=HTMLArea.editorUrl||'';if(typeof(plugin)!="undefined"){url+="plugins/"+plugin+"/";}
url+=style;if(/^\//.test(style)){url=style;}}
var head=document.getElementsByTagName("head")[0];var link=document.createElement("link");link.rel="stylesheet";link.href=url;head.appendChild(link);};HTMLArea.Editor.prototype.popupURL=function(file){var url="";if(file.match(/^plugin:\/\/(.*?)\/(.*)/)){var pluginId=RegExp.$1;var popup=RegExp.$2;if(!/\.html$/.test(popup))popup+=".html";if(this.config.pathToPluginDirectory[pluginId]){url=this.config.pathToPluginDirectory[pluginId]+"popups/"+popup;}else{url=HTMLArea.editorUrl+"plugins/"+pluginId+"/popups/"+popup;}}else{url=HTMLArea.editorUrl+this.config.popupURL+file;}
return url;};HTMLArea.getInnerText=function(el){var txt='',i;if(el.firstChild){for(i=el.firstChild;i;i=i.nextSibling){if(i.nodeType==3)txt+=i.data;else if(i.nodeType==1)txt+=HTMLArea.getInnerText(i);}}else{if(el.nodeType==3)txt=el.data;}
return txt;};HTMLArea.Editor.prototype.forceRedraw=function(){this.htmlArea.doLayout();};HTMLArea.Editor.prototype.focusEditor=function(){this.focus();return this.document;};HTMLArea.Editor.prototype.hasOpenedWindow=function(){for(var plugin in this.plugins){if(this.plugins.hasOwnProperty(plugin)){if(HTMLArea.Dialog[plugin.name]&&HTMLArea.Dialog[plugin.name].hasOpenedWindow&&HTMLArea.Dialog[plugin.name].hasOpenedWindow()){return true;}}}
return false};HTMLArea.Editor.prototype.updateToolbar=function(noStatus){this.toolbar.update(noStatus);};HTMLArea.Editor.prototype.surroundHTML=function(startTag,endTag){this.insertHTML(startTag+this.getSelectedHTML().replace(HTMLArea.Reg_body,"")+endTag);};HTMLArea.Editor.prototype.convertNode=function(el,newTagName){var newel=this.document.createElement(newTagName),p=el.parentNode;while(el.firstChild)newel.appendChild(el.firstChild);p.insertBefore(newel,el);p.removeChild(el);return newel;};HTMLArea.getElementObject=function(el,tagName){var oEl=el;while(oEl!=null&&oEl.nodeName.toLowerCase()!=tagName)oEl=oEl.parentNode;return oEl;};HTMLArea.Editor.prototype.removeMarkup=function(element){var bookmark=this.getBookmark(this._createRange(this._getSelection()));var parent=element.parentNode;while(element.firstChild){parent.insertBefore(element.firstChild,element);}
parent.removeChild(element);this.selectRange(this.moveToBookmark(bookmark));};HTMLArea.hasAllowedAttributes=function(element,allowedAttributes){var value;for(var i=allowedAttributes.length;--i>=0;){value=element.getAttribute(allowedAttributes[i]);if(value){if(allowedAttributes[i]=="style"&&element.style.cssText){return true;}else{return true;}}}
return false;};HTMLArea.Editor.prototype.hasSelectedText=function(){return this.getSelectedHTML()!="";};HTMLArea.Editor.prototype.getAllAncestors=function(){var p=this.getParentElement();var a=[];while(p&&(p.nodeType===1)&&(p.nodeName.toLowerCase()!=="body")){a.push(p);p=p.parentNode;}
a.push(this.document.body);return a;};HTMLArea.Editor.prototype.getBlockAncestors=function(element,withinBlock){var ancestors=new Array();var ancestor=element;while(ancestor&&(ancestor.nodeType===1)&&!/^(body)$/i.test(ancestor.nodeName)&&ancestor!=withinBlock){if(HTMLArea.isBlockElement(ancestor)){ancestors.unshift(ancestor);}
ancestor=ancestor.parentNode;}
ancestors.unshift(ancestor);return ancestors;};HTMLArea.Editor.prototype.getEndBlocks=function(selection){var range=this._createRange(selection);if(!Ext.isIE){var parentStart=range.startContainer;if(/^(body)$/i.test(parentStart.nodeName)){parentStart=parentStart.firstChild;}
var parentEnd=range.endContainer;if(/^(body)$/i.test(parentEnd.nodeName)){parentEnd=parentEnd.lastChild;}}else{if(selection.type!=="Control"){var rangeEnd=range.duplicate();range.collapse(true);var parentStart=range.parentElement();rangeEnd.collapse(false);var parentEnd=rangeEnd.parentElement();}else{var parentStart=range.item(0);var parentEnd=parentStart;}}
while(parentStart&&!HTMLArea.isBlockElement(parentStart)){parentStart=parentStart.parentNode;}
while(parentEnd&&!HTMLArea.isBlockElement(parentEnd)){parentEnd=parentEnd.parentNode;}
return{start:parentStart,end:parentEnd};};HTMLArea.Editor.prototype.endPointsInSameBlock=function(){var selection=this._getSelection();if(this._selectionEmpty(selection)){return true;}else{var parent=this.getParentElement(selection);var endBlocks=this.getEndBlocks(selection);return(endBlocks.start===endBlocks.end&&!/^(table|thead|tbody|tfoot|tr)$/i.test(parent.nodeName));}};HTMLArea.Editor.prototype._getFirstAncestor=function(sel,types){var prnt=this._activeElement(sel);if(prnt==null){try{prnt=(Ext.isIE?this._createRange(sel).parentElement():this._createRange(sel).commonAncestorContainer);}catch(e){return null;}}
if(typeof(types)=='string')types=[types];while(prnt){if(prnt.nodeType==1){if(types==null)return prnt;for(var i=0;i<types.length;i++){if(prnt.tagName.toLowerCase()==types[i])return prnt;}
if(prnt.tagName.toLowerCase()=='body')break;if(prnt.tagName.toLowerCase()=='table')break;}
prnt=prnt.parentNode;}
return null;};HTMLArea.Editor.prototype.getFullySelectedNode=function(selection,range,ancestors){var node,fullNodeSelected=false;if(!selection){var selection=this._getSelection();}
if(!this._selectionEmpty(selection)){if(!range){var range=this._createRange(selection);}
if(!Ext.isIE){if(range.startContainer.nodeType===3&&range.startOffset==range.startContainer.textContent.length&&range.startContainer.nextSibling.textContent==range.toString()){fullNodeSelected=true;node=range.startContainer.nextSibling;}
if(!fullNodeSelected&&range.endContainer.nodeType===3&&range.endOffset==0&&range.endContainer.previousSibling.textContent==range.toString()){fullNodeSelected=true;node=range.endContainer.previousSibling;}}
if(!fullNodeSelected){if(!ancestors){var ancestors=this.getAllAncestors();}
Ext.each(ancestors,function(ancestor){if(Ext.isIE){fullNodeSelected=(selection.type!=='Control'&&ancestor.innerText==range.text)||(selection.type==='Control'&&ancestor.innerText==range.item(0).text);}else{fullNodeSelected=(ancestor.textContent==range.toString());}
if(fullNodeSelected){node=ancestor;return false;}});}
if(Ext.isWebKit&&!fullNodeSelected){var statusBarSelection=this.statusBar?this.statusBar.getSelection():null;if(statusBarSelection&&statusBarSelection.textContent==range.toString()){fullNodeSelected=true;node=statusBarSelection;}}}
return fullNodeSelected?node:null;};HTMLArea.Editor.prototype.execCommand=function(cmdID,UI,param){this.focus();switch(cmdID){default:try{this.document.execCommand(cmdID,UI,param);}catch(e){if(this.config.debug)alert(e+"\n\nby execCommand("+cmdID+");");}}
this.toolbar.update();return false;};HTMLArea.Editor.prototype.scrollToCaret=function(){if(!Ext.isIE){var e=this.getParentElement(),w=this._iframe.contentWindow?this._iframe.contentWindow:window,h=w.innerHeight||w.height,d=this.document,t=d.documentElement.scrollTop||d.body.scrollTop;if(e.offsetTop>h+t||e.offsetTop<t){this.getParentElement().scrollIntoView();}}};HTMLArea.checkSupportedBrowser=function(){return Ext.isGecko||Ext.isWebKit||Ext.isOpera||Ext.isIE;};HTMLArea._removeClass=function(el,className,substring){if(!el||!el.className)return;var classes=el.className.trim().split(" ");var newClasses=new Array();for(var i=classes.length;--i>=0;){if(!substring){if(classes[i]!=className){newClasses[newClasses.length]=classes[i];}}else if(classes[i].indexOf(className)!=0){newClasses[newClasses.length]=classes[i];}}
if(newClasses.length==0){if(!Ext.isOpera){el.removeAttribute("class");if(Ext.isIE){el.removeAttribute("className");}}else{el.className='';}}else{el.className=newClasses.join(" ");}};HTMLArea._addClass=function(el,addClassName){HTMLArea._removeClass(el,addClassName);if(el.className&&HTMLArea.classesXOR&&HTMLArea.classesXOR.hasOwnProperty(addClassName)&&typeof(HTMLArea.classesXOR[addClassName].test)=="function"){var classNames=el.className.trim().split(" ");for(var i=classNames.length;--i>=0;){if(HTMLArea.classesXOR[addClassName].test(classNames[i])){HTMLArea._removeClass(el,classNames[i]);}}}
if(el.className)el.className+=" "+addClassName;else el.className=addClassName;};HTMLArea._hasClass=function(el,className,substring){if(!el||!el.className)return false;var classes=el.className.trim().split(" ");for(var i=classes.length;--i>=0;){if(classes[i]==className||(substring&&classes[i].indexOf(className)==0))return true;}
return false;};HTMLArea.isBlockElement=function(el){return el&&el.nodeType==1&&HTMLArea.RE_blockTags.test(el.nodeName.toLowerCase());};HTMLArea.needsClosingTag=function(el){return el&&el.nodeType==1&&!HTMLArea.RE_noClosingTag.test(el.tagName.toLowerCase());};HTMLArea.htmlDecode=function(str){str=str.replace(/&lt;/g,"<").replace(/&gt;/g,">");str=str.replace(/&nbsp;/g,"\xA0");str=str.replace(/&quot;/g,"\x22");str=str.replace(/&#39;/g,"'");str=str.replace(/&amp;/g,"&");return str;};HTMLArea.htmlEncode=function(str){if(typeof(str)!='string')str=str.toString();str=str.replace(/&/g,"&amp;");str=str.replace(/</g,"&lt;").replace(/>/g,"&gt;");str=str.replace(/\xA0/g,"&nbsp;");str=str.replace(/\x22/g,"&quot;");return str;};HTMLArea.getHTML=function(root,outputRoot,editor){try{return HTMLArea.getHTMLWrapper(root,outputRoot,editor);}catch(e){HTMLArea._appendToLog("The HTML document is not well-formed.");if(!HTMLArea.enableDebugMode)alert(HTMLArea.I18N.msg["HTML-document-not-well-formed"]);else return HTMLArea.getHTMLWrapper(root,outputRoot,editor);return editor.document.body.innerHTML;}};HTMLArea.getHTMLWrapper=function(root,outputRoot,editor){var html="";if(!root)return html;switch(root.nodeType){case 1:case 11:case 9:var closed,i,config=editor.config;var root_tag=(root.nodeType==1)?root.tagName.toLowerCase():'';if(root_tag=="br"&&config.removeTrailingBR&&!root.nextSibling&&HTMLArea.isBlockElement(root.parentNode)&&(!root.previousSibling||root.previousSibling.nodeName.toLowerCase()!="br")){if(!root.previousSibling&&root.parentNode&&root.parentNode.nodeName.toLowerCase()=="p"&&root.parentNode.className)html+="&nbsp;";break;}
if(config.htmlRemoveTagsAndContents&&config.htmlRemoveTagsAndContents.test(root_tag))break;var custom_tag=(config.customTags&&config.customTags.test(root_tag));if(outputRoot)outputRoot=!(config.htmlRemoveTags&&config.htmlRemoveTags.test(root_tag));if(outputRoot){if(Ext.isGecko&&root.hasAttribute('_moz_editor_bogus_node'))break;closed=(!(root.hasChildNodes()||HTMLArea.needsClosingTag(root)||custom_tag));html="<"+root_tag;var a,name,value,attrs=root.attributes;var n=attrs.length;for(i=attrs.length;--i>=0;){a=attrs.item(i);name=a.nodeName.toLowerCase();if((!a.specified&&name!='value')||/_moz|contenteditable|_msh|complete/.test(name))continue;if(!Ext.isIE||name!="style"){if(typeof(root[a.nodeName])!="undefined"&&name!="href"&&name!="src"&&name!="style"&&!/^on/.test(name)){value=root[a.nodeName];}else{value=a.nodeValue;if(Ext.isIE&&(name=="href"||name=="src")&&editor.plugins.link&&editor.plugins.link.instance&&editor.plugins.link.instance.stripBaseURL){value=editor.plugins.link.instance.stripBaseURL(value);}}}else{value=root.style.cssText;}
if(/(_moz|^$)/.test(value))continue;if(Ext.isIE&&root_tag=="li"&&name=="value"&&value==0)continue;if(name==='id'&&value.substr(0,7)==='ext-gen'){continue;}
html+=" "+name+'="'+HTMLArea.htmlEncode(value)+'"';}
if(html!="")html+=closed?" />":">";}
for(i=root.firstChild;i;i=i.nextSibling){if(/^li$/i.test(i.tagName)&&!/^[ou]l$/i.test(root.tagName))html+="<ul>"+HTMLArea.getHTMLWrapper(i,true,editor)+"</ul>";else html+=HTMLArea.getHTMLWrapper(i,true,editor);}
if(outputRoot&&!closed)html+="</"+root_tag+">";break;case 3:html=/^(script|style)$/i.test(root.parentNode.tagName)?root.data:HTMLArea.htmlEncode(root.data);break;case 8:if(!editor.config.htmlRemoveComments)html="<!--"+root.data+"-->";break;case 4:html+='<![CDATA['+root.data+']]>';break;case 5:html+='&'+root.nodeValue+';';break;case 7:html+='<?'+root.target+' '+root.data+' ?>';break;default:break;}
return html;};HTMLArea.getPrevNode=function(node){if(!node)return null;if(node.previousSibling)return node.previousSibling;if(node.parentNode)return node.parentNode;return null;};HTMLArea.getNextNode=function(node){if(!node)return null;if(node.nextSibling)return node.nextSibling;if(node.parentNode)return node.parentNode;return null;};HTMLArea.removeFromParent=function(el){if(!el.parentNode)return;var pN=el.parentNode;pN.removeChild(el);return el;};HTMLArea.util.Tips=function(){return{tipsOnFormFields:function(){if(this.helpText||this.helpTitle){if(!this.helpDisplay){this.helpDisplay='both';}
var label=this.label;if(label&&this.helpIcon&&!Ext.isIE){var helpImage=label.insertFirst({tag:'img',src:HTMLArea.editorSkin+'images/system-help-open.png',style:'vertical-align: middle; padding-right: 2px;'});if(this.helpDisplay=='image'||this.helpDisplay=='both'){Ext.QuickTips.register({target:helpImage,title:this.helpTitle,text:this.helpText});}}
if(this.helpDisplay=='field'||this.helpDisplay=='both'){Ext.QuickTips.register({target:this,title:this.helpTitle,text:this.helpText});}}},tipsOnMenuItems:function(){if(this.helpText||this.helpTitle){Ext.QuickTips.register({target:this,title:this.helpTitle,text:this.helpText});}}}}();Ext.form.Field.prototype.afterRender=Ext.form.Field.prototype.afterRender.createInterceptor(HTMLArea.util.Tips.tipsOnFormFields);Ext.menu.BaseItem.prototype.afterRender=Ext.menu.BaseItem.prototype.afterRender.createInterceptor(HTMLArea.util.Tips.tipsOnMenuItems);HTMLArea.util.Color=function(){return{colorToRgb:function(v){if(typeof(v)!='number'){return v;}
var r=v&0xFF;var g=(v>>8)&0xFF;var b=(v>>16)&0xFF;return'rgb('+r+','+g+','+b+')';},colorToHex:function(v){if(!v){return'';}
function hex(d){return(d<16)?('0'+d.toString(16)):d.toString(16);};if(typeof(v)=='number'){var b=v&0xFF;var g=(v>>8)&0xFF;var r=(v>>16)&0xFF;return'#'+hex(r)+hex(g)+hex(b);}
if(v.substr(0,3)==='rgb'){var re=/rgb\s*\(\s*([0-9]+)\s*,\s*([0-9]+)\s*,\s*([0-9]+)\s*\)/;if(v.match(re)){var r=parseInt(RegExp.$1);var g=parseInt(RegExp.$2);var b=parseInt(RegExp.$3);return('#'+hex(r)+hex(g)+hex(b)).toUpperCase();}
return null;}
if(v.substr(0,1)==='#'){return v;}
return null;},checkIfColorInPalette:function(color){if(this.el&&!this.el.child('a.color-'+color)){this.deSelect();return false;}}}}();HTMLArea._makeColor=HTMLArea.util.Color.colorToRgb;HTMLArea._colorToRgb=HTMLArea.util.Color.colorToHex;Ext.ColorPalette.prototype.select=Ext.ColorPalette.prototype.select.createInterceptor(HTMLArea.util.Color.checkIfColorInPalette);Ext.override(Ext.ColorPalette,{deSelect:function(){if(this.el&&this.value){this.el.child('a.color-'+this.value).removeClass('x-color-palette-sel');this.value=null;}}});Ext.ux.menu.HTMLAreaColorMenu=Ext.extend(Ext.menu.Menu,{enableScrolling:false,hideOnClick:true,cls:'x-color-menu',colorPaletteValue:'',customColorsValue:'',plain:true,showSeparator:false,initComponent:function(){var paletteItems=[];var width='auto';if(this.colorsConfiguration){paletteItems.push({xtype:'container',layout:'anchor',width:160,style:{float:'right'},items:{xtype:'colorpalette',itemId:'custom-colors',cls:'htmlarea-custom-colors',colors:this.colorsConfiguration,value:this.value,allowReselect:true,tpl:new Ext.XTemplate('<tpl for="."><a href="#" class="color-{1}" hidefocus="on"><em><span style="background:#{1}" unselectable="on">&#160;</span></em><span unselectable="on">{0}<span></a></tpl>')}});}
if(this.colors.length){paletteItems.push({xtype:'container',layout:'anchor',items:{xtype:'colorpalette',itemId:'color-palette',cls:'color-palette',colors:this.colors,value:this.value,allowReselect:true}});}
if(this.colorsConfiguration&&this.colors.length){width=350;}
Ext.apply(this,{layout:'menu',width:width,items:paletteItems});Ext.ux.menu.HTMLAreaColorMenu.superclass.initComponent.call(this);this.standardPalette=this.find('itemId','color-palette')[0];this.customPalette=this.find('itemId','custom-colors')[0];if(this.standardPalette){this.standardPalette.purgeListeners();this.relayEvents(this.standardPalette,['select']);}
if(this.customPalette){this.customPalette.purgeListeners();this.relayEvents(this.customPalette,['select']);}
this.on('select',this.menuHide,this);if(this.handler){this.on('select',this.handler,this.scope||this);}},menuHide:function(){if(this.hideOnClick){this.hide(true);}}});Ext.reg('htmlareacolormenu',Ext.ux.menu.HTMLAreaColorMenu);Ext.ux.form.ColorPaletteField=Ext.extend(Ext.form.TriggerField,{triggerClass:'x-form-color-trigger',defaultColors:['000000','222222','444444','666666','999999','BBBBBB','DDDDDD','FFFFFF','660000','663300','996633','003300','003399','000066','330066','660066','990000','993300','CC9900','006600','0033FF','000099','660099','990066','CC0000','CC3300','FFCC00','009900','0066FF','0000CC','663399','CC0099','FF0000','FF3300','FFFF00','00CC00','0099FF','0000FF','9900CC','FF0099','CC3333','FF6600','FFFF33','00FF00','00CCFF','3366FF','9933FF','FF00FF','FF6666','FF6633','FFFF66','66FF66','00FFFF','3399FF','9966FF','FF66FF','FF9999','FF9966','FFFF99','99FF99','99FFFF','66CCFF','9999FF','FF99FF','FFCCCC','FFCC99','FFFFCC','CCFFCC','CCFFFF','99CCFF','CCCCFF','FFCCFF'],colorizeFieldBackgroud:true,colorizeFieldText:true,colorizeTrigger:false,editable:true,initComponent:function(){Ext.ux.form.ColorPaletteField.superclass.initComponent.call(this);if(!this.colors){this.colors=this.defaultColors;}
this.addEvents('select');},validateBlur:function(){return!this.menu||!this.menu.isVisible();},setValue:function(color){if(color){if(this.colorizeFieldBackgroud){this.el.applyStyles('background: #'+color+';');}
if(this.colorizeFieldText){this.el.applyStyles('color: #'+this.rgbToHex(this.invert(this.hexToRgb(color)))+';');}
if(this.colorizeTrigger){this.trigger.applyStyles('background-color: #'+color+';');}}
return Ext.ux.form.ColorPaletteField.superclass.setValue.call(this,color);},onDestroy:function(){Ext.destroy(this.menu);Ext.ux.form.ColorPaletteField.superclass.onDestroy.call(this);},onTriggerClick:function(){if(this.disabled){return;}
if(this.menu==null){this.menu=new Ext.ux.menu.HTMLAreaColorMenu({hideOnClick:false,colors:this.colors,colorsConfiguration:this.colorsConfiguration,value:this.getValue()});}
this.onFocus();this.menu.show(this.el,"tl-bl?");this.menuEvents('on');},menuEvents:function(method){this.menu[method]('select',this.onSelect,this);this.menu[method]('hide',this.onMenuHide,this);this.menu[method]('show',this.onFocus,this);},onSelect:function(m,d){this.setValue(d);this.fireEvent('select',this,d);this.menu.hide();},onMenuHide:function(){this.focus(false,60);this.menuEvents('un');},invert:function(r,g,b){if(r instanceof Array){return this.invert.call(this,r[0],r[1],r[2]);}
return[255-r,255-g,255-b];},hexToRgb:function(hex){return[this.hexToDec(hex.substr(0,2)),this.hexToDec(hex.substr(2,2)),this.hexToDec(hex.substr(4,2))];},hexToDec:function(hex){var s=hex.split('');return((this.getHCharPos(s[0])*16)+this.getHCharPos(s[1]));},getHCharPos:function(c){var HCHARS='0123456789ABCDEF';return HCHARS.indexOf(c.toUpperCase());},rgbToHex:function(r,g,b){if(r instanceof Array){return this.rgbToHex.call(this,r[0],r[1],r[2]);}
return this.decToHex(r)+this.decToHex(g)+this.decToHex(b);},decToHex:function(n){var HCHARS='0123456789ABCDEF';n=parseInt(n,10);n=(!isNaN(n))?n:0;n=(n>255||n<0)?0:n;return HCHARS.charAt((n-n%16)/16)+HCHARS.charAt(n%16);}});Ext.reg('colorpalettefield',Ext.ux.form.ColorPaletteField);HTMLArea.getElementById=function(tag,id){var el,i,objs=document.getElementsByTagName(tag);for(i=objs.length;--i>=0&&(el=objs[i]);){if(el.id==id)return el;}
return null;};var lorem_ipsum=function(element,text){if(element.tagName.toLowerCase()=="textarea"&&element.id&&element.id.substr(0,7)=="RTEarea"){var editor=RTEarea[element.id.substr(7,element.id.length)]["editor"];editor.insertHTML(text);editor.toolbar.update();}};HTMLArea.initEditor=function(editorNumber){if(document.getElementById('pleasewait'+editorNumber)){if(HTMLArea.checkSupportedBrowser()){document.getElementById('pleasewait'+editorNumber).style.display='block';document.getElementById('editorWrap'+editorNumber).style.visibility='hidden';if(!HTMLArea.isReady){HTMLArea.initEditor.defer(150,null,[editorNumber]);}else{HTMLArea._appendToLog("[HTMLArea::initEditor]: Initializing editor with editor Id: "+editorNumber+".");var editor=new HTMLArea.Editor(Ext.apply(new HTMLArea.Config(editorNumber),RTEarea[editorNumber]));editor.generate();return false;}}else{document.getElementById('pleasewait'+editorNumber).style.display='none';document.getElementById('editorWrap'+editorNumber).style.visibility='visible';}}};HTMLArea.Base=function(){if(arguments.length){if(this==window){HTMLArea.Base.prototype.extend.call(arguments[0],arguments.callee.prototype);}else{this.extend(arguments[0]);}}};HTMLArea.Base.version="1.0.2";HTMLArea.Base.prototype={extend:function(source,value){var extend=HTMLArea.Base.prototype.extend;if(arguments.length==2){var ancestor=this[source];if((ancestor instanceof Function)&&(value instanceof Function)&&ancestor.valueOf()!=value.valueOf()&&/\bbase\b/.test(value)){var method=value;value=function(){var previous=this.base;this.base=ancestor;var returnValue=method.apply(this,arguments);this.base=previous;return returnValue;};value.valueOf=function(){return method;};value.toString=function(){return String(method);};}
return this[source]=value;}else if(source){var _prototype={toSource:null};var _protected=["toString","valueOf"];if(HTMLArea.Base._prototyping)_protected[2]="constructor";for(var i=0;(name=_protected[i]);i++){if(source[name]!=_prototype[name]){extend.call(this,name,source[name]);}}
for(var name in source){if(!_prototype[name]){extend.call(this,name,source[name]);}}}
return this;},base:function(){}};HTMLArea.Base.extend=function(_instance,_static){var extend=HTMLArea.Base.prototype.extend;if(!_instance)_instance={};HTMLArea.Base._prototyping=true;var _prototype=new this;extend.call(_prototype,_instance);var constructor=_prototype.constructor;_prototype.constructor=this;delete HTMLArea.Base._prototyping;var klass=function(){if(!HTMLArea.Base._prototyping)constructor.apply(this,arguments);this.constructor=klass;};klass.prototype=_prototype;klass.extend=this.extend;klass.implement=this.implement;klass.toString=function(){return String(constructor);};extend.call(klass,_static);var object=constructor?klass:_prototype;return object;};HTMLArea.Base.implement=function(_interface){if(_interface instanceof Function)_interface=_interface.prototype;this.prototype.extend(_interface);};HTMLArea.Plugin=HTMLArea.Base.extend({constructor:function(editor,pluginName){this.editor=editor;this.editorNumber=editor.editorId;this.editorId=editor.editorId;this.editorConfiguration=editor.config;this.name=pluginName;try{this.I18N=HTMLArea.I18N[this.name];}catch(e){this.I18N=new Object();}
return this.configurePlugin(editor);},configurePlugin:function(editor){return false;},registerPluginInformation:function(pluginInformation){if(typeof(pluginInformation)!=="object"){this.appendToLog("registerPluginInformation","Plugin information was not provided");return false;}else{this.pluginInformation=pluginInformation;this.pluginInformation.name=this.name;this.pluginInformation.developer_url=this.pluginInformation.developerUrl;this.pluginInformation.c_owner=this.pluginInformation.copyrightOwner;this.pluginInformation.sponsor_url=this.pluginInformation.sponsorUrl;return true;}},getPluginInformation:function(){return this.pluginInformation;},getPluginInstance:function(pluginName){return this.editor.getPlugin(pluginName);},getEditorMode:function(){return this.editor.getMode();},isButtonInToolbar:function(buttonId){var index=-1;Ext.each(this.editorConfiguration.toolbar,function(row){Ext.each(row,function(group){index=group.indexOf(buttonId);return index===-1;});return index===-1;});return index!==-1;},getButton:function(buttonId){return this.editor.toolbar.getButton(buttonId);},registerButton:function(buttonConfiguration){if(this.isButtonInToolbar(buttonConfiguration.id)){if(Ext.isString(buttonConfiguration.action)&&Ext.isFunction(this[buttonConfiguration.action])){buttonConfiguration.plugins=this;if(buttonConfiguration.dialog){if(!buttonConfiguration.dimensions){buttonConfiguration.dimensions={width:250,height:250};}
buttonConfiguration.dimensions.top=buttonConfiguration.dimensions.top?buttonConfiguration.dimensions.top:this.editorConfiguration.dialogueWindows.defaultPositionFromTop;buttonConfiguration.dimensions.left=buttonConfiguration.dimensions.left?buttonConfiguration.dimensions.left:this.editorConfiguration.dialogueWindows.defaultPositionFromLeft;}
buttonConfiguration.hidden=buttonConfiguration.hide;if(this.editorConfiguration.buttons[this.editorConfiguration.convertButtonId[buttonConfiguration.id]]){Ext.applyIf(buttonConfiguration,this.editorConfiguration.buttons[this.editorConfiguration.convertButtonId[buttonConfiguration.id]]);}
if(this.editorConfiguration.registerButton(buttonConfiguration)){var hotKey=buttonConfiguration.hotKey?buttonConfiguration.hotKey:((this.editorConfiguration.buttons[this.editorConfiguration.convertButtonId[buttonConfiguration.id]]&&this.editorConfiguration.buttons[this.editorConfiguration.convertButtonId[buttonConfiguration.id]].hotKey)?this.editorConfiguration.buttons[this.editorConfiguration.convertButtonId[buttonConfiguration.id]].hotKey:null);if(!hotKey&&buttonConfiguration.hotKey=="0"){hotKey="0";}
if(!hotKey&&this.editorConfiguration.buttons[this.editorConfiguration.convertButtonId[buttonConfiguration.id]]&&this.editorConfiguration.buttons[this.editorConfiguration.convertButtonId[buttonConfiguration.id]].hotKey=="0"){hotKey="0";}
if(hotKey||hotKey=="0"){var hotKeyConfiguration={id:hotKey,cmd:buttonConfiguration.id};return this.registerHotKey(hotKeyConfiguration);}
return true;}}else{this.appendToLog("registerButton","Function "+buttonConfiguration.action+" was not defined when registering button "+buttonConfiguration.id);}}
return false;},registerDropDown:function(dropDownConfiguration){if(this.isButtonInToolbar(dropDownConfiguration.id)){if(Ext.isString(dropDownConfiguration.action)&&Ext.isFunction(this[dropDownConfiguration.action])){dropDownConfiguration.plugins=this;dropDownConfiguration.hidden=dropDownConfiguration.hide;dropDownConfiguration.xtype='htmlareacombo';if(this.editorConfiguration.buttons[this.editorConfiguration.convertButtonId[dropDownConfiguration.id]]){Ext.applyIf(dropDownConfiguration,this.editorConfiguration.buttons[this.editorConfiguration.convertButtonId[dropDownConfiguration.id]]);}
return this.editorConfiguration.registerButton(dropDownConfiguration);}else{this.appendToLog('registerDropDown','Function '+dropDownConfiguration.action+' was not defined when registering drop-down '+dropDownConfiguration.id);}}
return false;},registerText:function(textConfiguration){if(this.isButtonInToolbar(textConfiguration.id)){textConfiguration.plugins=this;textConfiguration.xtype='htmlareatoolbartext';return this.editorConfiguration.registerButton(textConfiguration);}
return false;},getDropDownConfiguration:function(dropDownId){return this.editorConfiguration.buttonsConfig[dropDownId];},registerHotKey:function(hotKeyConfiguration){return this.editorConfiguration.registerHotKey(hotKeyConfiguration);},translateHotKey:function(key){if(typeof(this.editorConfiguration.hotKeyList[key])!=="undefined"){var buttonId=this.editorConfiguration.hotKeyList[key].cmd;if(typeof(buttonId)!=="undefined"){return buttonId;}else{return"";}}
return"";},getHotKeyConfiguration:function(key){if(Ext.isDefined(this.editorConfiguration.hotKeyList[key])){return this.editorConfiguration.hotKeyList[key];}else{return null;}},init:Ext.emptyFn,onUpdateToolbar:Ext.emptyFn,onKeyPress:null,onMode:function(mode){if(mode==="textmode"&&this.dialog&&HTMLArea.Dialog[this.name]==this.dialog&&!(this.dialog.buttonId&&this.editorConfiguration.buttons[this.dialog.buttonId]&&this.editorConfiguration.buttons[this.dialog.buttonId].textMode)){this.dialog.close();}},onGenerate:Ext.emptyFn,makeFunctionReference:function(functionName){var self=this;return(function(arg1,arg2,arg3){return(self[functionName](arg1,arg2,arg3));});},localize:function(label){return this.I18N[label]||HTMLArea.I18N.dialogs[label]||HTMLArea.I18N.tooltips[label]||HTMLArea.I18N.msg[label];},getJavascriptFile:function(url,callback){var success=false;this.appendToLog('getJavascriptFile','Requesting script '+url);Ext.Ajax.request({method:'GET',url:url,callback:callback,success:function(response){success=true;},failure:function(response){this.editor.inhibitKeyboardInput=false;this.appendToLog('getJavascriptFile','Unable to get '+url+' . Server reported '+response.status);},scope:this});return success;},postData:function(url,data,callback){var success=false;data.charset=this.editorConfiguration.typo3ContentCharset?this.editorConfiguration.typo3ContentCharset:'utf-8';var params='';Ext.iterate(data,function(parameter,value){params+=(params.length?'&':'')+parameter+'='+encodeURIComponent(value);});params+=this.editorConfiguration.RTEtsConfigParams;this.appendToLog('postData','Posting to '+url+'. Data: '+params);Ext.Ajax.request({method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8'},url:url,params:params,callback:Ext.isFunction(callback)?callback:function(options,success,response){if(success){this.appendToLog('postData','Post request to '+url+' successful. Server response: '+response.responseText);}else{this.appendToLog('postData','Post request to '+url+' failed. Server reported '+response.status);}},success:function(response){success=true;},failure:function(response){this.appendToLog('postData','Unable to post '+url+' . Server reported '+response.status);},scope:this});return success;},openDialog:function(buttonId,url,action,arguments,dimensions,showScrollbars,dialogOpener){if(this.dialog&&this.dialog.hasOpenedWindow()&&this.dialog.buttonId===buttonId){this.dialog.focus();return this.dialog;}else{var actionFunctionReference=action;if(typeof(action)==="string"){if(typeof(this[action])==="function"){var actionFunctionReference=this.makeFunctionReference(action);}else{this.appendToLog("openDialog","Function "+action+" was not defined when opening dialog for "+buttonId);}}
return new HTMLArea.Dialog(this,buttonId,url,actionFunctionReference,arguments,this.getWindowDimensions(dimensions,buttonId),(showScrollbars?showScrollbars:"no"),dialogOpener);}},openContainerWindow:function(buttonId,title,dimensions,url){this.dialog=new Ext.Window({id:this.editor.editorId+buttonId,title:this.localize(title)||title,cls:'htmlarea-window',width:dimensions.width,height:dimensions.height,border:false,iconCls:this.getButton(buttonId).iconCls,listeners:{afterrender:{fn:this.onContainerResize},resize:{fn:this.onContainerResize},close:{fn:this.onClose,scope:this}},items:{xtype:'box',itemId:'content-iframe',autoEl:{tag:'iframe',cls:'content-iframe',src:url}}});this.show();},onContainerResize:function(panel){var iframe=panel.getComponent('content-iframe');if(iframe.rendered){iframe.getEl().setSize(panel.getInnerWidth(),panel.getInnerHeight());}},getWindowDimensions:function(dimensions,buttonId){var dialogueWindowDimensions={width:250,height:250,top:this.editorConfiguration.dialogueWindows.defaultPositionFromTop,left:this.editorConfiguration.dialogueWindows.defaultPositionFromLeft};if(this.editorConfiguration.buttonsConfig[buttonId]){Ext.apply(dialogueWindowDimensions,this.editorConfiguration.buttonsConfig[buttonId].dimensions);}
Ext.apply(dialogueWindowDimensions,dimensions);var buttonConfiguration=this.editorConfiguration.buttons[this.editorConfiguration.convertButtonId[buttonId]];if(buttonConfiguration&&buttonConfiguration.dialogueWindow){Ext.apply(dialogueWindowDimensions,buttonConfiguration.dialogueWindow);if(buttonConfiguration.dialogueWindow.top){dialogueWindowDimensions.top=buttonConfiguration.dialogueWindow.positionFromTop;}
if(buttonConfiguration.dialogueWindow.left){dialogueWindowDimensions.left=buttonConfiguration.dialogueWindow.positionFromLeft;}}
return dialogueWindowDimensions;},makeUrlFromPopupName:function(popupName){return(popupName?this.editor.popupURL("plugin://"+this.name+"/"+popupName):this.editor.popupURL("blank.html"));},makeUrlFromModulePath:function(modulePath,parameters){return modulePath+'?'+this.editorConfiguration.RTEtsConfigParams+'&editorNo='+this.editor.editorId+'&sys_language_content='+this.editorConfiguration.sys_language_content+'&contentTypo3Language='+this.editorConfiguration.typo3ContentLanguage+'&contentTypo3Charset='+encodeURIComponent(this.editorConfiguration.typo3ContentCharset)+(parameters?parameters:'');},appendToLog:function(functionName,text){HTMLArea._appendToLog('['+this.name+'::'+functionName+']: '+text);},addConfigElement:function(configElement,configArray){if(!Ext.isEmpty(configElement)){configArray.push(configElement);}},syncHeight:function(tabPanel,tab){var position=this.dialog.getPosition();if(position[0]>0){this.dialog.setPosition(position);}},show:function(){this.dialog.mon(this.editor,'modeChange',this.close,this,{single:true});this.saveSelection();this.dialog.show();this.restoreSelection();},close:function(){this.saveSelection();this.dialog.close();},onClose:function(){this.editor.focus();this.restoreSelection();this.editor.updateToolbar();},onCancel:function(){this.dialog.close();this.editor.focus();},saveSelection:function(){if(Ext.isIE){this.savedRange=this.editor._createRange(this.editor._getSelection());}},restoreSelection:function(){if(Ext.isIE&&this.savedRange){try{this.editor.selectRange(this.savedRange);}catch(e){}}},buildButtonConfig:function(button,handler){return{xtype:'button',text:this.localize(button),listeners:{click:{fn:handler,scope:this}}};}});HTMLArea.Dialog=HTMLArea.Base.extend({constructor:function(plugin,buttonId,url,action,arguments,dimensions,showScrollbars,dialogOpener){this.window=window.window?window.window:window.self;this.plugin=plugin;this.buttonId=buttonId;this.action=action;if(typeof(arguments)!=="undefined"){this.arguments=arguments;}
this.plugin.dialog=this;if(HTMLArea.Dialog[this.plugin.name]&&HTMLArea.Dialog[this.plugin.name].hasOpenedWindow()&&HTMLArea.Dialog[this.plugin.name].plugin!=this.plugin){HTMLArea.Dialog[this.plugin.name].close();}
HTMLArea.Dialog[this.plugin.name]=this;this.dialogWindow=window.open(url,this.plugin.name+"Dialog","toolbar=no,location=no,directories=no,menubar=no,resizable=yes,top="+dimensions.top+",left="+dimensions.left+",dependent=yes,dialog=yes,chrome=no,width="+dimensions.width+",height="+dimensions.height+",scrollbars="+showScrollbars);if(!this.dialogWindow){this.plugin.appendToLog("openDialog","Dialog window could not be opened with url "+url);return false;}
if(typeof(dialogOpener)!=="undefined"){this.dialogWindow.opener=dialogOpener;this.dialogWindow.opener.openedDialog=this;}
if(!this.dialogWindow.opener){this.dialogWindow.opener=this.window;}
return true;},addButtons:function(){var self=this;var div=this.document.createElement("div");this.content.appendChild(div);div.className="buttons";for(var i=0;i<arguments.length;++i){var btn=arguments[i];var button=this.document.createElement("button");div.appendChild(button);switch(btn){case"ok":button.innerHTML=this.plugin.localize("OK");button.onclick=function(){try{self.callFormInputHandler();}catch(e){};return false;};break;case"cancel":button.innerHTML=this.plugin.localize("Cancel");button.onclick=function(){self.close();return false;};break;}}},callFormInputHandler:function(){var tags=["input","textarea","select"];var params=new Object();for(var ti=tags.length;--ti>=0;){var tag=tags[ti];var els=this.content.getElementsByTagName(tag);for(var j=0;j<els.length;++j){var el=els[j];var val=el.value;if(el.nodeName.toLowerCase()=="input"){if(el.type=="checkbox"){val=el.checked;}}
params[el.name]=val;}}
this.action(this,params);return false;},hasOpenedWindow:function(){return this.dialogWindow&&!this.dialogWindow.closed;},initialize:function(noLocalize,noResize,noStyle){this.dialogWindow.HTMLArea=HTMLArea;this.dialogWindow.dialog=this;this.captureEvents();if(!noStyle)this.loadStyle();if(!noLocalize)this.localize();if(!noResize)this.resize(noResize);},loadStyle:function(){var head=this.dialogWindow.document.getElementsByTagName("head")[0];var link=this.dialogWindow.document.createElement("link");link.rel="stylesheet";link.type="text/css";link.href=HTMLArea.editorCSS;if(link.href.indexOf("http")==-1&&!Ext.isIE)link.href=HTMLArea.hostUrl+link.href;head.appendChild(link);},localize:function(){var label;var types=["input","label","option","select","legend","span","td","button","div","h1","h2","a"];for(var type=0;type<types.length;++type){var elements=this.dialogWindow.document.getElementsByTagName(types[type]);for(var i=elements.length;--i>=0;){var element=elements[i];if(element.firstChild&&element.firstChild.data){label=this.plugin.localize(element.firstChild.data);if(label)element.firstChild.data=label;}
if(element.title){label=this.plugin.localize(element.title);if(label)element.title=label;}
if(types[type]=="option"&&element.selected){element.selected=false;element.selected=true;}}}
label=this.plugin.localize(this.dialogWindow.document.title);if(label)this.dialogWindow.document.title=label;},resize:function(noResize){var buttonConfiguration=this.plugin.editorConfiguration.buttons[this.plugin.editorConfiguration.convertButtonId[this.buttonId]];if(!this.plugin.editorConfiguration.dialogueWindows.doNotResize&&(!buttonConfiguration||!buttonConfiguration.dialogueWindow||!buttonConfiguration.dialogueWindow.doNotResize)){var dialogWindow=this.dialogWindow;var doc=dialogWindow.document;var content=doc.getElementById("content");if(Ext.isGecko||((Ext.isIE||Ext.isOpera||(Ext.isWebKit&&!Ext.isChrome))&&content)){var self=this;setTimeout(function(){if(!noResize){if(content){self.resizeToContent(content);}else if(dialogWindow.sizeToContent){dialogWindow.sizeToContent();}}
self.centerOnParent();},75);}else if(!noResize){var body=doc.body;if(Ext.isIE){var innerX=(doc.documentElement&&doc.documentElement.clientWidth)?doc.documentElement.clientWidth:body.clientWidth;var innerY=(doc.documentElement&&doc.documentElement.clientHeight)?doc.documentElement.clientHeight:body.clientHeight;var pageY=Math.max(body.scrollHeight,body.offsetHeight);if(innerY==pageY){dialogWindow.resizeTo(body.scrollWidth,body.scrollHeight+80);}else{dialogWindow.resizeBy((innerX<body.scrollWidth)?(Math.max(body.scrollWidth,body.offsetWidth)-innerX):0,(body.scrollHeight-body.offsetHeight));}}else if(Ext.isSafari||Ext.isOpera){dialogWindow.resizeTo(dialogWindow.innerWidth,body.offsetHeight+10);if(dialogWindow.innerHeight<body.scrollHeight){dialogWindow.resizeBy(0,(body.scrollHeight-dialogWindow.innerHeight)+10);}}
this.centerOnParent();}else{this.centerOnParent();}}else{this.centerOnParent();}},resizeToContent:function(content){var dialogWindow=this.dialogWindow;var doc=dialogWindow.document;var docElement=doc.documentElement;var body=doc.body;var width=0,height=0;var contentWidth=content.offsetWidth;var contentHeight=content.offsetHeight;if(Ext.isGecko||Ext.isWebKit){dialogWindow.resizeTo(contentWidth,contentHeight+(Ext.isWebKit?40:(Ext.isGecko2?75:95)));}else{dialogWindow.resizeTo(contentWidth+200,contentHeight+200);if(dialogWindow.innerWidth){width=dialogWindow.innerWidth;height=dialogWindow.innerHeight;}else if(docElement&&docElement.clientWidth){width=docElement.clientWidth;height=docElement.clientHeight;}else if(body&&body.clientWidth){width=body.clientWidth;height=body.clientHeight;}
dialogWindow.resizeTo(contentWidth+((contentWidth+200)-width),contentHeight+((contentHeight+200)-(height-16)));}},centerOnParent:function(){var buttonConfiguration=this.plugin.editorConfiguration.buttons[this.plugin.editorConfiguration.convertButtonId[this.buttonId]];if(!this.plugin.editorConfiguration.dialogueWindows.doNotCenter&&(!buttonConfiguration||!buttonConfiguration.dialogueWindow||!buttonConfiguration.dialogueWindow.doNotCenter)){var dialogWindow=this.dialogWindow;var doc=dialogWindow.document;var body=doc.body;if(!Ext.isIE){var x=dialogWindow.opener.screenX+(dialogWindow.opener.outerWidth-dialogWindow.outerWidth)/2;var y=dialogWindow.opener.screenY+(dialogWindow.opener.outerHeight-dialogWindow.outerHeight)/2;}else{var W=body.offsetWidth;var H=body.offsetHeight;var x=(screen.availWidth-W)/2;var y=(screen.availHeight-H)/2;}
if(!Ext.isChrome){try{dialogWindow.moveTo(x,y);}catch(e){}}}},performAction:function(val){if(val&&this.action){this.action(val);}},focus:function(){if(this.hasOpenedWindow()){this.dialogWindow.focus();}},close:function(){if(this.dialogWindow){try{if(this.dialogWindow.openedDialog){this.dialogWindow.openedDialog.close();}}catch(e){}
HTMLArea.Dialog[this.plugin.name]=null;if(!this.dialogWindow.closed){this.dialogWindow.dialog=null;if(Ext.isWebKit||Ext.isIE){this.dialogWindow.blur();}
this.dialogWindow.close();if(!this.dialogWindow.closed){this.dialogWindow=null;}}
if(this.plugin.editor._iframe){this.plugin.editor.toolbar.update();}}
return false;},makeFunctionReference:function(functionName){var self=this;return(function(arg1,arg2){self[functionName](arg1,arg2);});},closeOnEscape:function(event){var ev=event.browserEvent;if(ev.keyCode==27){if(!Ext.isIE){var parentWindow=ev.currentTarget.defaultView;}else{var parentWindow=ev.srcElement.parentNode.parentNode.parentWindow;}
if(parentWindow&&parentWindow.dialog){if(typeof(parentWindow.onEscape)=="function"){parentWindow.onEscape(ev);}
if(parentWindow.dialog){parentWindow.dialog.close();}
return false;}}
return true;},captureEvents:function(skipUnload){if(!Ext.isIE&&this.plugin.editor._iframe.contentWindow){Ext.EventManager.on(this.plugin.editor._iframe.contentWindow,'unload',this.close,this,{single:true});}
if(!skipUnload){Ext.EventManager.on(this.dialogWindow,'unload',this.close,this,{single:true});}
Ext.EventManager.on(this.dialogWindow.document,'keypress',this.closeOnEscape,this,{single:true});}});}